- bundle.Dockerfile
- bundle/manifests/backplane-operator-controller-manager-metrics-service_v1_service.yaml
- bundle/manifests/backplane-operator-controller-manager_v1_serviceaccount.yaml
- bundle/manifests/backplane-operator-manager-config_v1_configmap.yaml
- bundle/manifests/backplane-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/backplane-operator.clusterserviceversion.yaml
- bundle/manifests/backplane.open-cluster-management.io_backplaneconfigs.yaml
- bundle/metadata/annotations.yaml
- bundle/tests/scorecard/config.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/backplane-operator.clusterserviceversion.yaml
> Generate OLM bundle

- CONTRIBUTING.md
- DCO
- LICENSE
- OWNERS
- README.md
- SECURITY.md
- api/v1alpha1/backplaneconfig_types.go
- api/v1alpha1/groupversion_info.go
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/suite_test.go
- licensetest/license_test.go
- main.go
- pkg/foundation/cluster_manager.go
- pkg/foundation/cluster_manager_test.go
- pkg/foundation/foundation.go
- pkg/hive/hiveconfig.go
- pkg/utils/utils.go
- pkg/version/base.go
- pkg/version/version.go
Story: https://github.com/open-cluster-management/backlog/issues/14552
> License and contributing documents

- api/v1alpha1/backplaneconfig_types.go
- bundle.Dockerfile
- bundle/manifests/backplane-operator.clusterserviceversion.yaml
- bundle/manifests/backplane.open-cluster-management.io_backplaneconfigs.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/backplane.open-cluster-management.io_backplaneconfigs.yaml
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
User story: https://github.com/open-cluster-management/backlog/issues/14551
> Add phase status to api

- bundle/manifests/backplane-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/backplaneconfig_resources.go
- go.mod
- pkg/foundation/cluster_manager.go
- pkg/hive/hiveconfig.go
- pkg/rendering/renderer.go
- pkg/utils/utils.go
https://github.com/open-cluster-management/backlog/issues/14711
> 14711 add finalizer logic

- Dockerfile.prow
- Makefile.prow
- sonar-project.properties
> setup prow

- hack/catalog/subscription.yaml
Temp fix until code to deploy this is moved over to deploy repo in PR - https://github.com/open-cluster-management/deploy/pull/200
> Fix Channel

- pkg/templates/charts/server-foundation/templates/ocm-proxyserver-svc.yaml
- pkg/templates/charts/server-foundation/templates/ocm-webhook-svc.yaml
Signed-off-by: Zhiwei <zyin@redhat.com>
> fix the different labels of ocm deployment and service

- PROJECT
- api/v1alpha1/multiclusterengine_types.go
- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- config/manifests/bases/multicluster-engine.clusterserviceversion.yaml
- config/manifests/kustomization.yaml
https://github.com/open-cluster-management/backlog/issues/15632
> rename csv to multicluster-engine

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/suite_test.go
- go.mod
- go.sum
- main.go
https://github.com/open-cluster-management/backlog/issues/15633
> Watch subcomponents

- api/v1alpha1/multiclusterengine_types.go
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- hack/bundle-automation/generate-bundles.py
- pkg/rendering/renderer.go
- pkg/rendering/renderer_test.go
- pkg/templates/charts/cluster-manager/templates/cluster-manager.yaml
- pkg/templates/charts/hive-operator/templates/hive-operator.yaml
- pkg/templates/charts/server-foundation/templates/ocm-controller.yaml
- pkg/templates/charts/server-foundation/templates/ocm-proxyserver.yaml
- pkg/templates/charts/server-foundation/templates/ocm-webhook.yaml
- test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
> add image pull secret

- pkg/rendering/renderer.go
- pkg/rendering/renderer_test.go
>  propagate proxy variables

- Makefile.dev
- hack/bundle-automation/generate-bundles.py
- pkg/foundation/cluster_manager.go
- pkg/foundation/cluster_manager_test.go
- pkg/templates/charts/cluster-manager/templates/cluster-manager.yaml
- pkg/templates/charts/cluster-manager/values.yaml
- pkg/templates/charts/hive-operator/values.yaml
- pkg/templates/crds/cluster-manager/operator.open-cluster-management.io_clustermanagers.yaml
> update cluster manager

- api/v1alpha1/multiclusterengine_types.go
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- config/samples/multicluster_v1alpha1_multiclusterengine.yaml
- pkg/rendering/renderer_test.go
- test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
> Remove foo field from CRD

- .github/workflows/regenerate-operator-bundles.yml
- Makefile.dev
- hack/bundle-automation/csv_linter_rules.yaml
- hack/bundle-automation/generate-bundles.py
- hack/bundle-automation/validate_csv.py
https://github.com/open-cluster-management/backlog/issues/15491
> Lint Operator Bundles

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- pkg/templates/charts/server-foundation/templates/managedcluster-import-role.yaml
https://github.com/open-cluster-management/backlog/issues/16510
> Update managedclusterimport controller RBAC

- pkg/foundation/cluster_manager.go
- pkg/rendering/renderer.go
- pkg/utils/utils.go
>  add default tolerations to the cluster manager resource

- pkg/templates/charts/server-foundation/templates/webhook-mutating-config.yaml
- pkg/templates/charts/server-foundation/templates/webhook-validating-config.yaml
https://github.com/open-cluster-management/backlog/issues/18000
/hold
> Adds OCM webhook definitions

- README.md
> No-op change

- api/v1alpha1/multiclusterengine_webhook.go
/hold
https://github.com/open-cluster-management/backlog/issues/18086
> Allow installation with existing MCH

- api/v1alpha1/multiclusterengine_types.go
- api/v1alpha1/multiclusterengine_webhook.go
- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- config/manifests/bases/multicluster-engine.clusterserviceversion.yaml
- controllers/backplaneconfig_controller.go
- pkg/rendering/renderer.go
- pkg/rendering/renderer_test.go
- pkg/utils/utils.go
- test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
issue: https://github.com/stolostron/backlog/issues/16981
>  add availability configuration

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/manager/manager.yaml
>  add back pod namespace

- pkg/templates/charts/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
- pkg/templates/charts/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
- pkg/templates/charts/cluster-lifecycle/templates/provider-credential-controller-deployment.yaml
- pkg/templates/charts/server-foundation/templates/managedcluster-import-deployment.yaml
https://app.zenhub.com/workspaces/engineering-backlog-do-not-delete-604fab62d4b98d00150a2854/issues/stolostron/backlog/19864
> Add arm64 for MCE

- pkg/templates/crds/discovery-operator/discovery.open-cluster-management.io_discoveredclusters.yaml
- pkg/templates/crds/discovery-operator/discovery.open-cluster-management.io_discoveryconfigs.yaml
> Update Discovery CRDs

- api/v1/multiclusterengine_webhook.go
- pkg/templates/charts/discovery-operator/templates/role-leader-election.yaml
>  Canary fix

- pkg/templates/charts/always/cluster-lifecycle/templates/metrics-clusterrolebinding-prom.yaml
Signed-off-by: haoqing0110 <qhao@redhat.com>
> match clc-state-metrics ClusterRoleBinding to correct ClusterRole

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/samples/multicluster_v1_multiclusterengine.yaml
https://github.com/stolostron/backlog/issues/20018
> Fix Sample

- api/v1/multiclusterengine_webhook.go
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- controllers/backplaneconfig_controller.go
https://github.com/stolostron/backlog/issues/19782
> set default targetNamespace to multicluster-engine

- controllers/backplaneconfig_controller_test.go
- hack/bundle-automation/config.yaml
- pkg/templates/charts/always/assisted-service/Chart.yaml
- pkg/templates/charts/always/assisted-service/templates/assisted-service-clusterrole.yaml
- pkg/templates/charts/always/assisted-service/templates/assisted-service-clusterrolebinding.yaml
- pkg/templates/charts/always/assisted-service/templates/assisted-service-role.yaml
- pkg/templates/charts/always/assisted-service/templates/assisted-service-rolebinding.yaml
- pkg/templates/charts/always/assisted-service/templates/assisted-service-serviceaccount.yaml
- pkg/templates/charts/always/assisted-service/templates/infrastructure-operator.yaml
- pkg/templates/charts/always/assisted-service/values.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-admin-assisted-install.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-clusteradmin-assisted-install.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-edit-assisted-install.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-view-assisted-install.yaml
- pkg/templates/charts/always/rbac-aggregates/unused/clusterrole-admin-unused.yaml
- pkg/templates/charts/always/rbac-aggregates/unused/clusterrole-clusteradmin-unused.yaml
- pkg/templates/charts/always/rbac-aggregates/unused/clusterrole-edit-unused.yaml
- pkg/templates/charts/always/rbac-aggregates/unused/clusterrole-view-unused.yaml
- pkg/templates/crds/assisted-service/agent-install.openshift.io_agents.yaml
- pkg/templates/crds/assisted-service/agent-install.openshift.io_agentserviceconfigs.yaml
- pkg/templates/crds/assisted-service/agent-install.openshift.io_infraenvs.yaml
- pkg/templates/crds/assisted-service/agent-install.openshift.io_nmstateconfigs.yaml
- pkg/templates/crds/assisted-service/extensions.hive.openshift.io_agentclusterinstalls.yaml
- pkg/utils/utils.go
https://github.com/stolostron/backlog/issues/20009#event-6084900468
/hold
Must wait until AI images are in the manifests
> Onboard AI to MCE

- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
Signed-off-by: Zack Layne <zlayne@redhat.com>
> Add PlacementDecisions to console-clusterrole

- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-admin-managed-serviceaccount.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-clusteradmin-managed-serviceaccount.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-edit-managed-serviceaccount.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-view-managed-serviceaccount.yaml
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
> adding agg roles for managed serviceaccount

- pkg/templates/charts/toggle/console-mce/Chart.yaml
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
> Correct official MCE component name

- hack/bundle-automation/generate-charts.py
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
I tested the git action in my own fork this time (thanks Zack) and everything ran.
Running the action will result in chart changes, but that's good (I'll test those changes as part of the generated PR)
> updating script to run with python3

- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-admin-clc.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-clusteradmin-clc.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-edit-clc.yaml
- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-view-clc.yaml
> Add cluster-proxy-addon CRD

- controllers/backplaneconfig_controller.go
Issue: https://github.com/stolostron/backlog/issues/20599
> Allow console-mce to be toggled off in 4.10

- hack/bundle-automation/config.yaml
https://github.com/stolostron/backlog/issues/20726
> Pin Hive to mce-2.0

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager-clusterrole.yaml
Also removes my manual hack in the automated clustermanager deployment since this file is autogenerated
> Ensures bundled CSV is up to date

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
Allows addon deployment to function as expected
https://github.com/stolostron/backlog/issues/20775
> Ensure ReplicaCount of 1

- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
Signed-off-by: Zack Layne <zlayne@redhat.com>
> Add subscription.operators.coreos.com to console-clusterrole

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-configmap.yaml
- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
- pkg/templates/charts/toggle/hypershift/values.yaml
- pkg/utils/utils.go
> Onboard HyperShift Configmap

- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Issue: https://github.com/stolostron/backlog/issues/20901
> Collapse repeat components in spec to one

- controllers/backplaneconfig_controller.go
- controllers/toggle_components.go
- pkg/toggle/toggle.go
Issue: https://github.com/stolostron/backlog/issues/20782
> Proceed with deploying other components if one fails

- api/v1/multiclusterengine_types.go
- api/v1/multiclusterengine_webhook.go
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- config/manifests/bases/multicluster-engine.clusterserviceversion.yaml
- controllers/toggle_components.go
- pkg/rendering/renderer.go
Issue: https://github.com/stolostron/backlog/issues/21016
> Add static override to change assisted installer namespace

- pkg/templates/charts/toggle/hypershift/templates/hypershiftDeployment-deployment.yaml
> Change ReplicaCount to 1 for HyperShiftDeployment

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
> CRD adds new printer column

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
> Add new printer column and update CRD with hypershift:release-4.10

- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-clusterrole.yaml
https://github.com/stolostron/clusterclaims-controller/pull/39
> add lease permission

- api/v1/multiclusterengine_methods.go
> Name ManagedServiceAccount as preview

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
* Changed HOSTING -> PROGRESS
*  Added AVAILABLE
> Apply new HypershiftDeployment printcolumns

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Reference: https://github.com/openshift/hypershift/pull/1259
> Add support for spec.serviceAccountSigningKey. Issue 21690

- pkg/templates/crds/foundation/imageregistry.open-cluster-management.io_managedclusterimageregistries.yaml
issue: https://github.com/stolostron/backlog/issues/21706
> update imageregistry crd to fix issue 21706

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
The related issue: https://github.com/stolostron/backlog/issues/21003
Signed-off-by: Yang Le <yangle@redhat.com>
> update command of cluster curator

- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
fix issue: https://github.com/stolostron/backlog/issues/21838
> update rbac of import-controller to fix 21838

- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
Signed-off-by: zhujian <jiazhu@redhat.com>
https://github.com/stolostron/managedcluster-import-controller/pull/161 needs the permission to deletion addons.
> Add managedclusteraddon deletecollection permission for import controller

- controllers/toggle_components.go
Issue https://github.com/stolostron/backlog/issues/21739
> Enable mce plugin when console is toggled on

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
* Issue: https://github.com/stolostron/backlog/issues/22096
* Summary, we are keeping pace with Hypershift for Service Delivery consumption.
> Picking up latest CRD from hypershift-deployment-controller.

- controllers/backplaneconfig_controller_test.go
> add test for service monitor deletion

- hack/bundle-automation/chart-values/managed-serviceaccount/values.yaml
- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/generate-charts.py
- pkg/templates/charts/toggle/managed-serviceaccount/values.yaml
> Regenerate Charts using inclusion

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
https://issues.redhat.com/browse/ACM-1287
> Add HostedCluster and NodePool obj references to the HypershiftDeployment CRD

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Make `spec.infrastructure.cloudProvider` optional
> Rj acm 1407

- pkg/templates/charts/toggle/assisted-service/templates/assisted-service-clusterrole.yaml
- pkg/templates/crds/assisted-service/agent-install.openshift.io_agentserviceconfigs.yaml
> Regenerate bundles

- Makefile
- pkg/templates/crds/foundation/action.open-cluster-management.io_managedclusteractions_crd.yaml
- pkg/templates/crds/foundation/imageregistry.open-cluster-management.io_managedclusterimageregistries.yaml
- pkg/templates/crds/foundation/internal.open-cluster-management.io_managedclusterinfos_crd.yaml
- pkg/templates/crds/foundation/inventory.open-cluster-management.io_baremetalassets_crd.yaml
- pkg/templates/crds/foundation/view.open-cluster-management.io_managedclusterviews_crd.yaml
story: https://github.com/stolostron/backlog/issues/23216
> update foundation apis

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Signed-off-by: Roke Jung <roke@redhat.com>
https://github.com/stolostron/backlog/issues/23544
> Update hypershift deployment CRD

- Dockerfile
- Dockerfile.prow
- Dockerfile.test.prow
- go.mod
> update backplane-2.0 branch to go 1.18

- Dockerfile
- Dockerfile.prow
- Dockerfile.test.prow
- go.mod
> update backplane-1.0 branch to go 1.18

- Makefile
> add test-prep target to Makefile

- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
Issue: https://github.com/stolostron/backlog/issues/23581
> 23581 ensure secret

- .github/workflows/regenerate-operator-bundles-2.0.yml
- hack/bundle-automation/config.yaml
> Add cron to regenerate 2.0 bundles

- api/v1/multiclusterengine_types.go
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- main.go
- pkg/status/status.go
- pkg/status/status_test.go
- pkg/version/version.go
Issue: https://github.com/stolostron/backlog/issues/23776
> Add current and desired version to status

- pkg/templates/crds/foundation/inventory.open-cluster-management.io_baremetalassets_crd.yaml
https://github.com/stolostron/backlog/issues/24149
> deprecate bm asset

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
- pkg/templates/crds/hypershift/hypershift.openshift.io_hostedclusters.yaml
Signed-off-by: Roke Jung <roke@redhat.com>
Hypershift CRD updates for hypershift operator 4.11 latest
> update hypershift 4.11 operator and go module

- pkg/templates/charts/toggle/console-mce/templates/console-plugin.yaml
https://github.com/stolostron/backlog/issues/24467
> Add annotation to enable i18n in 4.11+

- pkg/templates/charts/toggle/console-mce/templates/console-plugin.yaml
https://github.com/stolostron/backlog/issues/24467
> [backplane-2.0] Add annotation to enable i18n in 4.11+

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Signed-off-by: Roke Jung <roke@redhat.com>
Updated HypershiftDeployment CRD
> update hypershiftdeployment CRD

- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
> add tokenrequest permission for import controller

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
https://github.com/stolostron/backlog/issues/24459
> Fix agent-image-name

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/managedproxyconfiguration.yaml
https://github.com/stolostron/backlog/issues/24468
> Fix: support config tolerations in nodePlacement

- hack/bundle-automation/config.yaml
Part of stolostron/backlog#24541
> Update commit used for Hive bundle stuff to MCE 2.1 feature-complete level

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>
> Add permissions to watch hypershift related resources

- api/v1/multicluster_methods_test.go
- controllers/backplaneconfig_controller_test.go
- pkg/foundation/cluster_manager_test.go
- pkg/utils/utils_test.go
- sonar-project.properties
>  improve tests

- pkg/templates/charts/always/rbac-aggregates/templates/clusterrole-clusteradmin-clc.yaml
Issue: https://github.com/stolostron/backlog/issues/23939
> Add applicationsets to cluster-manager-admin clusterrole

- pkg/templates/charts/toggle/discovery-operator/templates/discovery-operator.yaml
>  discovery TLS fix

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-service.yaml
> match cluster proxy service and pod selectors

- Makefile
- pkg/status/cluster_manager_test.go
- pkg/status/deployment_test.go
- pkg/status/status_test.go
Towards coverage effort https://github.com/stolostron/backlog/issues/22703
> Add status unit tests

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/anp-service.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/managedproxyconfiguration.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
https://github.com/stolostron/backlog/issues/24999
> Fix: cluster-proxy-addon chart

- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Required by https://github.com/stolostron/console/pull/1968
> Add permissions to list/watch multiclusterengine resources

- config/rbac/role.yaml
- go.mod
- go.sum
- pkg/rendering/renderer.go
- pkg/rendering/renderer_test.go
issue: https://github.com/stolostron/backlog/issues/24856
> fix tolerations types to always be string

- controllers/toggle_components.go
- pkg/utils/utils.go
- test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
> Remove references to deprecated hypershift deployment controller

- pkg/templates/charts/toggle/console-mce/templates/console-quickstart.yaml
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
https://github.com/stolostron/backlog/issues/26129
> Remove identity configuration management

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
This PR is related to a change in the community. https://github.com/open-cluster-management-io/cluster-proxy/pull/127
> Add a new flag for cluster-proxy deployments.

- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/hosted.go
- pkg/utils/annotations.go
- sonar-project.properties
Issue: https://github.com/stolostron/backlog/issues/26218
> Read hosted cluster creds from secret in target ns

- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- go.mod
- go.sum
- hack/unit-test-crds/clustermanagementaddons.addon.open-cluster-management.io.yaml
- pkg/templates/charts/toggle/server-foundation/templates/clusterrole-foundation.yaml
- pkg/templates/clustermanagementaddons/workmanager.yaml
- pkg/templates/rbac_gen.go
- test/mock-crds/clustermanagementaddons.addon.open-cluster-management.io.yaml
> support addondeploymentconfig for work mgr

- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/toggle_components.go
- pkg/status/console.go
- pkg/status/console_test.go
issue: https://github.com/stolostron/backlog/issues/25510
> MCE console uninstalls when OCP console unavailable

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
> ACM-1926 Correct typo for placementruless and add userpreferences

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/sevice-proxy-mpsr.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
The related issue: https://github.com/stolostron/backlog/issues/26546
The related fix PR: https://github.com/stolostron/cluster-proxy-addon/pull/81
> Update cluster-proxy-addon chart to fix a security issue.

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/service-proxy-mpsr.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
> Fix security issues cluster-proxy-addon.

- pkg/templates/clustermanagementaddons/workmanager.yaml
> let user configure the support configs for workmgr

- controllers/backplaneconfig_controller.go
- controllers/hosted.go
- pkg/foundation/hosted_cluster_manager.go
- pkg/utils/utils.go
- sonar-project.properties
Issue: https://github.com/stolostron/backlog/issues/26469
> Deploy clustermanager in hosted mode

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/clustermanagementaddon.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/clusterrole.yaml
- pkg/templates/rbac_gen.go
Related user-story: https://github.com/stolostron/backlog/issues/26489
> Add addonDeploymentConfig for cluster-proxy-addon.

- Dockerfile
- Dockerfile.prow
- Dockerfile.test.prow
- go.mod
> update to go 1.19

- main.go
Issue: https://github.com/stolostron/backlog/issues/26672
> Configure TLS minimum version to 1.2

- pkg/templates/crds/cluster-lifecycle/cluster.open-cluster-management.io_clustercurators.yaml
> update curator crd to support monitor timeout

- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/rbac/role.yaml
- hack/bundle-automation/config.yaml
- pkg/templates/charts/toggle/hive-operator/templates/hive-operator-clusterrole.yaml
- pkg/templates/crds/assisted-service/agent-install.openshift.io_infraenvs.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeploymentcustomizations.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeployments.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterpools.yaml
- pkg/templates/rbac_gen.go
Update hive bundle to sha 443b7d70c311205878105eb2e26156cadf5f5ce3
> Update hive bundle sha

- controllers/backplaneconfig_controller.go
- controllers/toggle_components.go
- pkg/status/console.go
- pkg/status/console_test.go
Issue: https://github.com/stolostron/backlog/issues/26671
Jira: https://issues.redhat.com/browse/ACM-1983
> MCE Console Fixes

- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/toggle_components.go
- pkg/status/console.go
- pkg/status/console_test.go
Issue: https://github.com/stolostron/backlog/issues/25511
The watch issue [here](https://github.com/stolostron/backlog/issues/26671) is still unresolved, we can hold this until I fix that or push this now and the fix later.
> MCE console uninstalls when OCP console unavailable (#310)

- api/v1/multiclusterengine_methods.go
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- controllers/backplaneconfig_controller.go
- controllers/toggle_components.go
- controllers/toggle_components_test.go
- hack/unit-test-crds/managedclusteraddons.yaml
- pkg/rendering/addon.go
- pkg/rendering/addon_test.go
- pkg/status/cluster_manager.go
- pkg/status/cluster_manager_test.go
- pkg/status/condition.go
- pkg/status/generic.go
- pkg/status/generic_test.go
- pkg/utils/utils.go
Issue: https://github.com/stolostron/backlog/issues/26215
> Hypershift local hosting addon

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
https://issues.redhat.com/browse/ACM-2183
> Increase mem limit for the cluster image set controller

- pkg/templates/crds/cluster-lifecycle/cluster.open-cluster-management.io_clustercurators.yaml
For https://issues.redhat.com/browse/ACM-1259
/assign @JakobGray 
/assign @xiangjingli 
/assign @jnpacker 
/assign @elgnay 
FYI @KevinFCormier @Randy424 
> Update Cluster Curator to add optional job_tags and skip_tags for AnsibleJob.

- pkg/templates/charts/toggle/managed-serviceaccount/templates/deployment.yaml
Fixes: https://issues.redhat.com/browse/ACM-2074
> Fix: add quick restart managed-serviceaccount after restore.

- api/v1/groupversion_info.go
- api/v1/multiclusterengine_types.go
- controllers/backplaneconfig_controller_test.go
- controllers/hosted.go
- controllers/toggle_components.go
- pkg/rendering/renderer.go
- pkg/templates/charts/hosted/server-foundation/Chart.yaml
- pkg/templates/charts/hosted/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/charts/hosted/server-foundation/templates/managedcluster-import-role_binding.yaml
- pkg/templates/charts/hosted/server-foundation/templates/managedcluster-import-service_account.yaml
- pkg/templates/charts/hosted/server-foundation/values.yaml
- pkg/templates/charts/hosting/server-foundation/Chart.yaml
- pkg/templates/charts/hosting/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/hosting/server-foundation/values.yaml
- pkg/templates/hosted-crds/managed-import/agent-install.openshift.io_infraenvs.yaml
- pkg/templates/hosted-crds/managed-import/hive.openshift.io_clusterdeployments.yaml
- pkg/toggle/toggle.go
- pkg/utils/utils.go
Issue:  https://github.com/stolostron/backlog/issues/26666
> 26666 import controller

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-clustermanagementaddon.yaml
- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
- pkg/templates/rbac_gen.go
> Add support to node selector and tolerations to the Hypershift addon

- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- docs/README.md
- pkg/utils/annotations.go
- pkg/utils/annotations_test.go
- pkg/version/version.go
- pkg/version/version_test.go
Issue: https://github.com/stolostron/backlog/issues/26481
> Report error phase when in unsupported OCP environment

- controllers/toggle_components.go
>  update cluster image status

- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Follow-up for https://github.com/stolostron/console/pull/2304
> Grant permissions for storageclass, agentserviceconfigs and clusterversions

- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/rbac_gen.go
The related jira: https://issues.redhat.com/browse/ACM-2163
Signed-off-by: Yang Le <yangle@redhat.com>
> add permissions to clusterlifecycle-state-metrics

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
https://issues.redhat.com/browse/ACM-2365
> Add pod ns env var for cluster image set controller

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-clusterrole.yaml
- pkg/templates/rbac_gen.go
fix issue:  https://issues.redhat.com/browse/ACM-2195
> update curator rbac

- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Signed-off-by: Kevin Cormier <kcormier@redhat.com>
> Fix typo in API name: storageclass -> storageclasses

- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- pkg/templates/charts/toggle/console-mce/templates/clusterimageset-clusterrole.yaml
- pkg/templates/charts/toggle/console-mce/templates/clusterimageset-clusterrolebinding.yaml
- pkg/templates/rbac_gen.go
Migrated from ACM. Issue: https://issues.redhat.com/browse/ACM-2203
> Add clusterimagesets clusterrole and crb

- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
> increase the import controller  memory limit to support more clusters

- pkg/templates/charts/toggle/console-mce/templates/console-configmap.yaml
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
regarding: https://issues.redhat.com/browse/ACM-2425
> ACM-2425 Enable Aws Private wizard steps

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/managedproxyconfiguration.yaml
Fixes: https://issues.redhat.com/browse/ACM-2520
> Fix imagepullsecret missing on agent-side.

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
Fixes: https://issues.redhat.com/browse/ACM-2530
> Fix: set enable-kube-api-proxy to false.

- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-controller.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
https://issues.redhat.com/browse/ACM-2626
https://issues.redhat.com/browse/ACM-2635
https://issues.redhat.com/browse/ACM-2627
> add golimit to clc repos

- controllers/backplaneconfig_controller.go
Jira: https://issues.redhat.com/browse/ACM-2782
~After code cutoff. Requires approval.~ Code cutoff was extended
> Wait on local-cluster delete before deleting cluster-manager

- .github/workflows/regenerate-operator-bundles-2.2.yml
- docs/override-images.md
- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/config.yaml
- hack/scripts/dev-update-image-references.py
> update github action

- pkg/templates/crds/cluster-lifecycle/cluster.open-cluster-management.io_clustercurators.yaml
> backport curator configurable timeout

- docs/override-crds.md
- main.go
- pkg/utils/annotations.go
- pkg/utils/annotations_test.go
Jira: https://issues.redhat.com/browse/ACM-2942
> Skip update on CRDs with label

- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
https://issues.redhat.com/browse/ACM-2835
> add golimit to clusterclaim repos

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-controller.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-webhook.yaml
https://issues.redhat.com/browse/ACM-3467
> increase limits  memory for clc/foundation deployments

- pkg/rendering/renderer.go
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Jira: [ACM-3270](https://issues.redhat.com/browse/ACM-3270)
> Add HUB_TYPE to clusterlifecycle-state-metrics-v2

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
Fixes: https://issues.redhat.com/browse/ACM-3208
> Fix: cluster-proxy doesn't work in BM proxy env.

- pkg/templates/charts/toggle/server-foundation/templates/webhook-validating-config.yaml
issue reference: https://issues.redhat.com/browse/ACM-3469
> make the ocm validating webhook to validate managed cluster deletion

- .github/workflows/rbac-gen.yml
- Dockerfile
- Dockerfile.prow
- Dockerfile.test.prow
- api/v1/groupversion_info.go
- api/v1/multiclusterengine_types.go
- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- controllers/toggle_components.go
- go.mod
- pkg/utils/utils.go
Jira: https://issues.redhat.com/browse/ACM-4310
> [backplane-2.1] Update Go to 1.20

- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
The related issue: https://issues.redhat.com/browse/ACM-4154
> use hub-type argument instead of env variable

- pkg/templates/crds/cluster-lifecycle/cluster.open-cluster-management.io_clustercurators.yaml
https://issues.redhat.com/browse/ACM-4654
- Update ClusterCurator CRD
> ACM-4654 Update ClusterCurator CRD

- main.go
issue: https://issues.redhat.com/browse/ACM-4517
> ACM-4517 Reduce cache usage by default in MCE

- hack/bundle-automation/generate-bundles.py
Update bundle generation to more closely match MCH's script
> [2.2] Update bundle generation

- hack/bundle-automation/generate-bundles.py
Update bundle generation to more closely match MCH's script
> Update bundle generation

- main.go
Jira: https://issues.redhat.com/browse/ACM-5226
> Update webhook server tls min version to 1.3

- pkg/templates/crds/foundation/internal.open-cluster-management.io_managedclusterinfos_crd.yaml
Fix issue: https://issues.redhat.com/browse/ACM-4647
> update managedclusterinfo crd

- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
Fixes: https://issues.redhat.com/browse/ACM-5428
> Fix:tls version error

- main.go
issue: https://issues.redhat.com/browse/ACM-5508
> ACM-5508 Change Logger Formatting

- hack/bundle-automation/config.yaml
Jira: https://issues.redhat.com/browse/ACM-5514
> ACM-5514: Update Hive SHA

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
issue: https://issues.redhat.com/browse/ACM-3072
> ACM-3072 Fix PodSecurity Warnings [Cluster-Proxy-Addon]

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-controller-deployment.yaml
issue: https://issues.redhat.com/browse/ACM-3072
> ACM-3072 Fix PodSecurity Warnings [Cluster-Lifecycle]

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
Reverts https://github.com/stolostron/backplane-operator/pull/433 and https://github.com/stolostron/backplane-operator/pull/434
> Revert changes to seccompProfile preventing deploy

- pkg/rendering/renderer_test.go
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-deployment.yaml
- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-controller.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-webhook.yaml
- pkg/templates/rbac.go
issue: https://issues.redhat.com/browse/ACM-3072
> Add seccompProfile optionally to charts in OCP 4.11+

- pkg/templates/charts/toggle/managed-serviceaccount/templates/deployment.yaml
> Add conditional seccompProfile for managed-serviceaccount

- hack/bundle-automation/config.yaml
- hack/bundle-automation/gen-hive-bundle.sh
- hack/bundle-automation/generate-bundles.py
- pkg/templates/crds/hive-operator/hive.openshift.io_checkpoints.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterclaims.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeploymentcustomizations.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeployments.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeprovisions.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterimagesets.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterpools.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterprovisions.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterrelocates.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterstates.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_dnszones.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_hiveconfigs.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_machinepoolnameleases.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_machinepools.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_selectorsyncidentityproviders.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_selectorsyncsets.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_syncidentityproviders.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_syncsets.yaml
- pkg/templates/crds/hive-operator/hiveinternal.openshift.io_clustersyncleases.yaml
- pkg/templates/crds/hive-operator/hiveinternal.openshift.io_clustersyncs.yaml
- pkg/templates/crds/hive-operator/hiveinternal.openshift.io_fakeclusterinstalls.yaml
Jira: https://issues.redhat.com/browse/ACM-5660
> Hive updates 2.2

- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager-clusterrole.yaml
reference: https://github.com/open-cluster-management-io/ocm/pull/223
> update cluster manager rbac

- controllers/toggle_components.go
Jira: https://issues.redhat.com/browse/ACM-5993
Example status immediately after disabling hypershift-preview:
```
- kind: Component
message: Waiting for 'hypershift-addon' ManagedClusterAddOn to be removed
name: hypershift-preview
reason: WaitingForResource
status: "False"
type: Uninstalled
- kind: Component
message: 'Local hosting only available when hypershift is enabled. The following
resources remain: <ManagedClusterAddOn local-cluster/hypershift-addon>'
name: hypershift-addon
reason: ResourcesPresent
status: "False"
type: NotPresent
````
> ACM-5993: Check hypershift-addon before uninstalling hypershift

- hack/bundle-automation/generate-charts.py
Adding to make sure the seccompProfile conditional is in any charts we pick up
> seccompProfile git actions fixes

- config/rbac/role.yaml
- go.mod
- go.sum
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-bootstrap-clusterrole.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-bootstrap-clusterrolebinding.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-bootstrap-serviceaccount.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-client-role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-route.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-service.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
Related issue: https://issues.redhat.com/browse/ACM-2252?focusedId=22684351&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22684351
Related PR: https://github.com/stolostron/managedcluster-import-controller/pull/265
> Support agent registration.

- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- pkg/templates/crds/foundation/config.open-cluster-management.io_klusterletconfigs_crd.yaml
The related issue: https://issues.redhat.com/browse/ACM-6325
> update klusterletconfig crd

- OWNERS
Updated OWNERS to match source of truth.
> [Automated PR] Resynced OWNERS file for backplane-2.0

- OWNERS
Updated OWNERS to match source of truth.
> [Automated PR] Resynced OWNERS file for backplane-2.3

- OWNERS
Updated OWNERS to match source of truth.
> [Automated PR] Resynced OWNERS file for backplane-2.2

- OWNERS
Updated OWNERS to match source of truth.
> [Automated PR] Resynced OWNERS file for backplane-2.1

- api/v1/multiclusterengine_methods.go
- controllers/backplaneconfig_controller.go
- pkg/utils/utils.go
Additionally, managedserviceaccount-preview will function in place of default during Reconcile loop
> removed preview from ManagedServiceAccount

- hack/bundle-automation/config.yaml
Updating the hive commit to resolve the error for the Github Action:
```
Error: branch arg 7f0e57561a44cbd062368d1c2a8e0f4e1825bf15 is not a valid tip of mce-* branch or master branch
Consider using the `--commit 7f0e57561a44cbd062368d1c2a8e0f4e1825bf15` argument if this commit is an ancestor of a valid
mce-* or master branch
```
N/A
Updated bundle automation `config.yaml` to include a later `mce-2.2` commit for `hive`.
> updated hive commit for GH action

- .github/workflows/regenerate-charts.yml
- .github/workflows/regenerate-operator-bundles-2.0.yml
- .github/workflows/regenerate-operator-bundles-2.1.yml
- .github/workflows/regenerate-operator-bundles-2.2.yml
- .github/workflows/regenerate-operator-bundles-2.3.yml
- .github/workflows/regenerate-operator-bundles.yml
- hack/bundle-automation/requirements.txt
> Updated github action scripts

- .github/workflows/regenerate-charts.yml
- .github/workflows/regenerate-operator-bundles-2.0.yml
- .github/workflows/regenerate-operator-bundles-2.1.yml
- .github/workflows/regenerate-operator-bundles-2.2.yml
- .github/workflows/regenerate-operator-bundles-2.3.yml
- .github/workflows/regenerate-operator-bundles.yml
- hack/bundle-automation/generate-bundles.py
Updating Github Actions to send slack notification if job fails.
N/A
Updated Github Action to alert team if failure occured.
N/A
> Updated github action workflow to send failure to slack

- .github/workflows/regenerate-operator-bundles-2.0.yml
- .github/workflows/regenerate-operator-bundles-2.1.yml
- .github/workflows/regenerate-operator-bundles-2.2.yml
- .github/workflows/regenerate-operator-bundles-2.3.yml
- .github/workflows/regenerate-operator-bundles.yml
Fixed conditional parameter for github action.
N/A
Removed extra space around conditional parameter for github action.
N/A
> Fixed github action conditional statement

- .github/workflows/regenerate-operator-bundles-2.0.yml
- .github/workflows/regenerate-operator-bundles-2.1.yml
- .github/workflows/regenerate-operator-bundles-2.2.yml
- .github/workflows/regenerate-operator-bundles-2.3.yml
- .github/workflows/regenerate-operator-bundles.yml
Updated GH actions to use `continue-on-error`.
N/A
Updated GH actions to use `continue-on-error`.
N/A
> Updated GitHub Action to continue upon failure

- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/rbac/role.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-clusterrole.yaml
- pkg/templates/rbac_gen.go
Add clusterroles and clusterrolebindings RBAC for ClusterCurator
https://issues.redhat.com/browse/ACM-7887
Add clusterroles and clusterrolebindings RBAC for ClusterCurator
> ACM-7887 Add clusterroles and clusterrolebindings RBAC for ClusterCurator

- .gitignore
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
> SCC V2 privileged and ro root filesystem

- .gitignore
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
This reverts commit ecd3af2e99b0b874afe5e80edc5bd0d028cab8c4.
Signed-off-by: Nathaniel Graham <[nathaniel.graham@protonmail.com, ngraham@redhat.com]>
> Revert "SCC V2 privileged and ro root filesystem (#539)"

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/manager/manager.yaml
> added SCC V2 compliance for privileged and rorfs

- hack/bundle-automation/config.yaml
- hack/bundle-automation/gen-hive-bundle.sh
Updated hive config to support latest hive commit from `mce-2.3` branch in `openshift/hive` repo.
N/A
Updated hive reference in hack/bundle-automation/config.yaml
/cc @cameronmwall @joeg-pro
> Updated hive commit to latest mce-2.3

- hack/bundle-automation/config.yaml
- hack/bundle-automation/gen-hive-bundle.sh
- hack/bundle-automation/generate-bundles.py
Updated hive config to support latest hive commit from `mce-2.2` branch in `openshift/hive repo`.
N/A
Updated hive reference in `hack/bundle-automation/config.yaml`.
> Updated hive commit to latest mce-2.2

- hack/bundle-automation/requirements.txt
Updated `requirements.txt` for `backplane-2.2` branch.
N/A
Updated requirements to include updated dependencies.
> Updated automation dependencies requirement file

- hack/bundle-automation/config.yaml
- hack/bundle-automation/gen-hive-bundle.sh
- hack/bundle-automation/generate-bundles.py
- hack/bundle-automation/requirements.txt
Updated GH action script to capture latest changes for `assisted-service` component.
N/A
Updated hack scripts to pull in latest changes or `assisted-service` component.
> Resolved Github Action failure for assisted-service

- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Removes unneeded permissions for console deployment
https://issues.redhat.com/browse/ACM-9150
- Remove argoproj.io/appprojects and organize by API group
/cc @JakobGray @fxiang1
> ACM-9150 Reduce permissions for console deployment

- hack/bundle-automation/chart-templates/Chart.yaml
- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/config.yaml
- pkg/templates/charts/always/rbac-aggregates/Chart.yaml
- pkg/templates/charts/hosted/server-foundation/Chart.yaml
- pkg/templates/charts/hosting/server-foundation/Chart.yaml
- pkg/templates/charts/toggle/assisted-service/Chart.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/Chart.yaml
- pkg/templates/charts/toggle/cluster-manager/Chart.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/Chart.yaml
- pkg/templates/charts/toggle/console-mce/Chart.yaml
- pkg/templates/charts/toggle/discovery-operator/Chart.yaml
- pkg/templates/charts/toggle/hive-operator/Chart.yaml
- pkg/templates/charts/toggle/hypershift/Chart.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/Chart.yaml
- pkg/templates/charts/toggle/server-foundation/Chart.yaml
Updated config files to use the current release version for MCE 2.5.
https://issues.redhat.com/browse/ACM-8310
- Updated bundle-automation config to point to `backplane-2.5` branches.
- Updated component templates `Chart.yaml` files to use version `2.5.0`.
> [ACM-8310] updated bundle-automation to use backplane-2.5

- controllers/toggle_components.go
> Updated controller to avoid potentials entries in nil map

- hack/bundle-automation/config.yaml
- hack/bundle-automation/generate-shell.py
Added the config file back for bundle generation and updated the wrapper script accordingly
https://issues.redhat.com/browse/ACM-8296
> bundle generation move with config

- config/rbac/role.yaml
- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager-clusterrole.yaml
- pkg/templates/rbac_gen.go
Add a patch permission of storageversionmigration/status for cluster-manager.
```yaml
apiVersion: migration.k8s.io/v1alpha1
kind: StorageVersionMigration
metadata:
creationTimestamp: "2023-11-29T20:28:13Z"
generation: 1
name: managedclustersets.v1beta1.cluster.open-cluster-management.io
resourceVersion: "438815282"
uid: e07fa7de-a7ce-40db-8e72-0931f84c4783
spec:
resource:
group: cluster.open-cluster-management.io
resource: managedclustersets
version: v1beta1
status:
conditions:
- lastUpdateTime: "2023-11-29T20:28:14Z"
message: 'failed to list resources: the server could not find the requested resource'
status: "True"
type: Failed 
```
In some of the 2.4.1 upgrade cases, we end up with the above failed storageversionmigration CR, we want to patch the status part to remove the Failed …
> Add status patch for cluster-manager.

- .github/workflows/regenerate-operator-bundles-2.0.yml
- .github/workflows/regenerate-operator-bundles-2.1.yml
- .github/workflows/regenerate-operator-bundles-2.2.yml
- .github/workflows/regenerate-operator-bundles-2.4.yml
- .github/workflows/regenerate-operator-bundles.yml
Added `backplane-2.4` regenerate-bundle Github action job.
Added `backplane-2.4` regenerate-bundle Github action job.
> Added GH action for backplane-2.4

- hack/bundle-automation/config.yaml
Updating `mce-2.3` hive commit to the latest.
https://issues.redhat.com/browse/ACM-9051
Updated bundle automation to support latest `mce-2.3` hive commit.
> [ACM-9051] Updated hive commit to latest mce-2.3

- hack/bundle-automation/config.yaml
Updating `mce-2.4` hive commit to the latest.
https://issues.redhat.com/browse/ACM-9051
Updated bundle automation to support latest `mce-2.4` hive commit.
> [ACM-9051] Updated hive commit to latest mce-2.4

- controllers/backplaneconfig_controller.go
- controllers/hosted.go
- controllers/toggle_components.go
- main.go
- pkg/rendering/renderer.go
- pkg/rendering/renderer_test.go
- test/unit-test-crds/extensions.hive.openshift.io_agentclusterinstalls.yaml
https://issues.redhat.com/browse/ACM-9281
> namespace to conversion

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
Add permissions on PriorityClass to the import controller.
https://issues.redhat.com/browse/ACM-6265
> add permissions on priorityclass to import controller

- hack/bundle-automation/config.yaml
- pkg/templates/charts/toggle/hive-operator/templates/hive-operator.yaml
- pkg/templates/crds/assisted-service/agent-install.openshift.io_agents.yaml
- pkg/templates/crds/cluster-manager/operator.open-cluster-management.io_clustermanagers.yaml
Updated `hive` commit for `mce-2.5`.
https://issues.redhat.com/browse/ACM-9051
Updated `hive` config to use latest `mce-2.5` commit for bundle-automation.
> [ACM-9051] Updated hive commit to latest mce-2.5

- hack/bundle-automation/chart-templates/values.yaml
- pkg/templates/charts/toggle/assisted-service/values.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/values.yaml
- pkg/templates/charts/toggle/cluster-manager/values.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/values.yaml
- pkg/templates/charts/toggle/discovery-operator/values.yaml
- pkg/templates/charts/toggle/hive-operator/values.yaml
- pkg/templates/charts/toggle/hypershift/values.yaml
- pkg/templates/charts/toggle/image-based-install-operator/values.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/values.yaml
- pkg/templates/charts/toggle/server-foundation/values.yaml
- pkg/templates/rbac_gen.go
Some of our tests are reporting template evaluation errors on Helm flow-control expressions regarding a semver test.  This is because the values.yaml being used for the tests either lacks a definition for Values.hubconfig.ocpVersion, or the value is a null string which isn't valid for such a test.  This PR should fix these.
- Adjust values.yaml files to add proper definition of Values.hubconfig.ocpVersion (using 4.12.0).
- Add null map for Values.templateOverrides to prepare for use of those overrides.
> Fix template evaluation errors in PR tests

- pkg/templates/charts/toggle/console-mce/templates/console-deployment.yaml
- pkg/templates/charts/toggle/console-mce/values.yaml
This PR provides template-override capability for  console-mce deployment cpu/memory requests and limits.  Four template-override keys are defined, one for each:
- `console_mce_deployment_container_memory_request`
- `console_mce_deployment_container_cpu_request`
- `console_mce_deployment_container_memory_limit`
- `console_mce_deployment_container_cpu_limit`
These template overrides can be defined using the mechanisms being implemented by PR #598.
If no template overrides are defined, the updated chart produces the same deployment as it does prior to this PR.  
- Add default (empty) global.templateOverrides to value.yaml (with comments about available overrides)
- Update console-deployment.yaml to use cpu/memory request and limit overrides if they are found to have been defined as …
> Enable template overrides for console-mce cpu/memory requests and limits

- pkg/templates/charts/toggle/image-based-install-operator/templates/image-based-install-config_v1_route.yaml
Adding template manifest file for ibio component `route`.
https://issues.redhat.com/browse/ACM-9922
Added route for ibio component.
> [ACM-9922] Added IBIO route to component template

- hack/bundle-automation/config.yaml
> fix-ibio-config

- hack/bundle-automation/chart-requirements.txt
> Updated chart requirements file

- Makefile.dev
- hack/bundle-automation/config.yaml
Updating `mce-2.4` hive commit to the latest.
Updated bundle automation to support latest `mce-2.4` hive commit.
/cc @cameronmwall @joeg-pro
> Update hive commit to latest mce-2.4

- api/v1/multiclusterengine_types.go
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- docs/available-components.md
- hack/bundle-automation/config.yaml
- pkg/templates/rbac_gen.go
update API descriptions
https://issues.redhat.com/browse/ACM-9483
https://issues.redhat.com/browse/ACM-8981
> Rewrite description

- api/v1/multiclusterengine_methods.go
- api/v1/multiclusterengine_methods_test.go
- api/v1/multiclusterengine_types.go
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
> Marshal hubSize from MCE spec

- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
update foundation helm chart to remove klusterlet cert.
issue: https://issues.redhat.com/browse/ACM-10784
> update ocm-proxyserver yaml to remove klusterlet cert

- go.mod
- go.sum
- main.go
> Updated go.mod to use compatible version for prometheus/common

- main.go
- pkg/templates/rbac_gen.go
Updating the manager options to increase the `cacheSyncTimeout` duration from `2m` (default) to `5m`.
https://issues.redhat.com/browse/ACM-11042
Updated `cacheSyncTimeout` to `5m`.
> [ACM-11042] Updated MCE manager cacheSyncTimeout duration to 5mins

- Makefile
Updating the `Makefile` controller-runtime `envtest` package version.
Updated version from `latest` to `release-0.17`.
> Updated Makefile to support compatible controller-runtime envtest

- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager-clusterrole.yaml
update the clusterrole of cluster-manager.
https://issues.redhat.com/browse/ACM-10667
> update cluster-manager rbac

- .github/workflows/regenerate-operator-bundles.yml
- hack/bundle-automation/config.yaml
- pkg/templates/crds/cluster-manager/operator.open-cluster-management.io_clustermanagers.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeployments.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeprovisions.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterpools.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_hiveconfigs.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_machinepools.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_selectorsyncsets.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_syncsets.yaml
Updated `hive` commit for `mce-2.6`.
https://issues.redhat.com/browse/ACM-11088
Updated `hive` config to use latest `mce-2.6` commit for bundle-automation.
> [ACM-11088] Updated hive commit to latest mce-2.6

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
- pkg/templates/rbac_gen.go
Allow the hypershift addon to use DiscoveredCluster resources.
https://issues.redhat.com/browse/ACM-11470
Added DiscoveredCluster in the ClusterRole
> ACM-11470: Allow DiscoveredCluster

- .github/workflows/regenerate-sha-commit.yml
- Makefile.dev
- hack/bundle-automation/gen-hive-bundle.sh
- hack/bundle-automation/generate-shell.py
Updated shell script to support new commit sha script.
https://issues.redhat.com/browse/ACM-11501
Updated `bundle-automation/generate-shell` script.
> [ACM-11501] Updated shell script for automation

- .github/workflows/regenerate-sha-commit.yml
- hack/bundle-automation/config.yaml
This PR will fix the `secret` reference for the Github Action job.
Updated `secret` reference in automation job.
> Updated automation secret ref

- .github/workflows/regenerate-operator-bundles.yml
Currently, this is blocker our automation from picking up newer changes from other components. We need to enhance the linter script and make it more robust to run in our automation; therefore, for now we will disable it.
> Disable linter in github action

- pkg/templates/clustermanagementaddons/workmanager.yaml
update install strategy of foundation addon
https://issues.redhat.com/browse/ACM-10679
update cma field to set install strategy
> Update install strategy for foundation addon

- pkg/templates/crds/foundation/config.open-cluster-management.io_klusterletconfigs_crd.yaml
update cluster-lifecycle-api to the latest
https://issues.redhat.com/projects/ACM/issues/ACM-11459?filter=myopenissues
> Update config API with installMode field

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/clustermanagementaddon.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
update cluster-proxy installStrategy
https://issues.redhat.com/browse/ACM-11745
> Update install strategy for cluster-proxy addon

- config/rbac/role.yaml
- pkg/templates/clustermanagementaddons/workmanager.yaml
- pkg/templates/rbac_gen.go
Add supported configs (addondeploymentconfig) for the work manager addon clustermanagementaddon
/cc @qiujian16 @haoqing0110
> Add supported configs for work manager addon

- .tekton/backplane-operator-qa7p-pull-request.yaml
- .tekton/backplane-operator-qa7p-push.yaml
- config/rbac/role.yaml
- pkg/templates/rbac_gen.go
There are some parameters the deprecation job needs which currently are not being passed.  The details are at this link:
https://github.com/konflux-ci/build-definitions/blob/main/task/deprecated-image-check/0.4/MIGRATION.md
Refs:
- https://issues.redhat.com/browse/ACM-10761
> Fix the missing parameters needed by konflux

- controllers/backplaneconfig_controller.go
In MCE 2.4, a regression introduced into our code: https://github.com/stolostron/backplane-operator/blob/backplane-2.4/controllers/backplaneconfig_controller.go#L232-L242.
We are attempting to apply the `openshift.io/cluster-monitoring` label to the `targetNamespace` before it is created by the MCE operator. Beforehand, if the `targetNamespace` did not exist, MCE would create it; however, since we are trying to apply the label before that validation happens, the regression was introduced. This PR will fix that issue by moving the label apply later on in the reconcile loop.
https://issues.redhat.com/browse/ACM-12132
Updated order for applying label for MCE operand's namespace.
Add any additional notes, context, or …
> [ACM-12132] Fixed standalone mce failing to install on custom namespace

- .github/workflows/regenerate-operator-bundles-2.6.yml
- .github/workflows/regenerate-sha-commit-2.6.yml
> Added GH Action config files for 2.6 automation

- .github/workflows/regenerate-operator-bundles-2.5.yml
- .github/workflows/regenerate-operator-bundles-2.6.yml
- Makefile.dev
- hack/bundle-automation/generate-shell.py
Associated installer dev tools PR: https://github.com/stolostron/installer-dev-tools/pull/22
> Renamed generate-charts.py to bundles-to-charts.py

- .github/workflows/regenerate-operator-bundles-2.6.yml
- .github/workflows/regenerate-operator-bundles.yml
Updating `regenerate-bundles` make command to use the latest renamed command.
https://issues.redhat.com/browse/ACM-11975
Updated `regenerate-bundles` to use latest command.
> [ACM-11975] Updated regenerate-operator-bundles make command

- pkg/templates/charts/toggle/managed-serviceaccount/templates/addontemplate.yaml
Run `make regenerate-charts` to update managed service account addon chart to fix https://issues.redhat.com/browse/ACM-12247
https://issues.redhat.com/browse/ACM-12247
> Update managed service account addon charts

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
Additional environment variables for the hypershift addon manager to find itself.
https://issues.redhat.com/browse/ACM-11310
> ACM-11310: additional env variables for hypershift addon manager

- hack/bundle-automation/generate-shell.py
Updated the shell script to ensure that the arguments are being parsed properly for the newly added commands.
Updated `generate-shell.py` script.
> Updated generate-shell.py to support new commands

- hack/bundle-automation/config.yaml
Updated hive to the latest commit: `0ed7370553a5b48808a8eabedeb1522497b9247b`.
https://issues.redhat.com/browse/ACM-12312
Updated hive `mce-2.6` commit to `0ed7370553a5b48808a8eabedeb1522497b9247b` in `config.yaml.`
> [ACM-12312] Updated hive commit to latest mce-2.6

- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Add OCP and Remote permissions to Service Account
ACM-11030
add permissions to allow a Service Account to list OCP apps and remote apps
> add service account permissions

- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/override-images.md
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @dislbenn  @cameronmwall `
> Updated README.md and CONTRIBUTING.md

- pkg/templates/charts/toggle/console-mce/templates/console-plugin.yaml
consolePlugin chart template for mce was updated from apiVersion v1alpha1 to v1
https://issues.redhat.com/browse/ACM-12354
consolePlugin chart template for mce was updated from apiVersion v1alpha1 to v1
> update consolePlugin chart template from v1alpha1 to v1

- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/config.yaml
> Updated automation release branch ref to MCE 2.7

- Dockerfile
- Dockerfile.prow
- Dockerfile.rhtap
- Dockerfile.test.prow
> Updated UBI image for Dockerfiles

- hack/bundle-automation/config.yaml
Updated `hive` component to MCE 2.7 branch.
Updated `hive` branch from `mce-2.6` to `mce-2.7`.
> Updated bundle-automation components to backplane-2.7

- pkg/templates/charts/toggle/managed-serviceaccount/templates/addontemplate.yaml
Re-adding `target.workload.openshift.io/management` annotation to `managed-serviceaccount` `addonTemplate` resource.                 
https://issues.redhat.com/browse/ACM-12987
Added `target.workload.openshift.io/management` annotation to `addonTemplate` resource.
> [ACM-12987] Regenerated charts for MCE 2.6

- pkg/utils/utils.go
> Updated IBIO component to be disabled by default

- pkg/templates/crds/foundation/config.open-cluster-management.io_klusterletconfigs_crd.yaml
Need to update the KlusterletConfigs CRD to provide the dev preview feature: https://issues.redhat.com/browse/ACM-11112
It's a direct a copy made from file: https://github.com/stolostron/cluster-lifecycle-api/blob/main/klusterletconfig/v1alpha1/config.open-cluster-management.io_klusterletconfigs.crd.yaml
> Update KlusterletConfigs CRD.

- api/v1/multiclusterengine_methods.go
- config/rbac/role.yaml
- pkg/templates/rbac_gen.go
https://issues.redhat.com/browse/ACM-12766
> [ACM-12766] Added configOverrides to component struct

- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager.yaml
- pkg/templates/charts/toggle/cluster-manager/values.yaml
- pkg/templates/rbac_gen.go
> aks revert

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-deploymentconfig.yaml
> aks hyper shift

- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
> updated CR deletion logic for when MCE goes away

- pkg/templates/charts/toggle/image-based-install-operator/templates/image-based-install-operator.yaml
> [Manual] Operator Bundle Update

- Makefile.dev
- hack/bundle-automation/generate-shell.py
> Updated shell script for automation

- .tekton/backplane-operator-mce-27-pull-request.yaml
- .tekton/backplane-operator-mce-27-push.yaml
Updating .tekton files to use the `backplane-2.7` branch, instead of the `main` branch.
> [2.7] Updated tekton files branch ref

- .github/workflows/regenerate-charts.yml
- .github/workflows/regenerate-operator-bundles-2.0.yml
- .github/workflows/regenerate-operator-bundles-2.1.yml
- .github/workflows/regenerate-operator-bundles-2.2.yml
- .github/workflows/regenerate-operator-bundles-2.4.yml
- .github/workflows/regenerate-operator-bundles-2.5.yml
- .github/workflows/regenerate-operator-bundles-2.7.yml
- .github/workflows/regenerate-sha-commit-2.7.yml
As we transition to MCE 2.8, this PR will add the Github actions files for MCE 2.7 to prepare for GA.
https://issues.redhat.com/browse/ACM-14819
> [ACM-14819] Added GH Action config files for 2.7 automation

- .github/renovate.json
Updated the `renovate.json` file to include the `backplane-2.7` branch as a `baseBranch` for konflux. This PR will ensure that the 2.7 konflux files are updated accordingly to our desired schedule.
Updated `baseBranches` in `renovate.json` to include `backplane-2.7`.
> Updated renovate.json to target 2.7 branch

- .github/workflows/regenerate-charts.yml
- .github/workflows/regenerate-operator-bundles.yml
- .github/workflows/regenerate-sha-commit.yml
> Updated github actions jobs to run in parallel

- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/config.yaml
Updated the `config.yaml` branch references to `backplane-2.8` or `main` (temporary).
https://issues.redhat.com/browse/ACM-14817
Updated release branch ref for automation to `backplane-2.8`.
> [ACM-14817] Update automation release branch ref to MCE 2.8

- config/rbac/role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
Fix conflict https://github.com/stolostron/backplane-operator/pull/1060#issuecomment-2454897478
cherry pick https://github.com/stolostron/backplane-operator/pull/1060
https://issues.redhat.com/browse/ACM-15058
> [backplane-2.6] Foundation: Add get list watch hostedcluster permission for import controller

- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Gives the console cluster role list & watch permissions for search-operator.
> console role list&watch search-operator permission

- config/rbac/role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
Fix conflict https://github.com/stolostron/backplane-operator/pull/1060#issuecomment-2454899034
cherry pick https://github.com/stolostron/backplane-operator/pull/1060
https://issues.redhat.com/browse/ACM-15057
> [backplane-2.5] Foundation: Add get list watch hostedcluster permission for import controller

- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-client-role.yaml
There is typo in the `managedcluster-import-controller` role. 
> Fix type `agent-regitration` to `agent-registration`

- .github/workflows/regenerate-sha-commit.yml
- Makefile.dev
- hack/bundle-automation/config.yaml
- pkg/templates/charts/toggle/hive-operator/templates/hive-operator.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeploymentcustomizations.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeployments.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeprovisions.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterpools.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_hiveconfigs.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_machinepools.yaml
> Updated hive commit to latest mce-2.8

- hack/bundle-automation/config.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_checkpoints.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterclaims.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeploymentcustomizations.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeployments.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterdeprovisions.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterimagesets.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterpools.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterprovisions.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterrelocates.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_clusterstates.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_dnszones.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_hiveconfigs.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_machinepoolnameleases.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_machinepools.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_selectorsyncidentityproviders.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_selectorsyncsets.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_syncidentityproviders.yaml
- pkg/templates/crds/hive-operator/hive.openshift.io_syncsets.yaml
- pkg/templates/crds/hive-operator/hiveinternal.openshift.io_clustersyncleases.yaml
- pkg/templates/crds/hive-operator/hiveinternal.openshift.io_clustersyncs.yaml
- pkg/templates/crds/hive-operator/hiveinternal.openshift.io_fakeclusterinstalls.yaml
> Updated hive commit to latest mce-2.4

- controllers/toggle_components.go
- main.go
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-rolebinding.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-service_account.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-rolebinding.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-service_account.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-rolebinding.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-service_account.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterrole-clustermanageradmin.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-clusterrolebinding-prom.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-prometheusrule.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-servicemonitor.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-clusterrolebinding.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-service_account.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/values.yaml
- pkg/templates/rbac_gen.go
- pkg/utils/utils.go
https://issues.redhat.com/browse/ACM-14477
> enable clusterlifecycle-metric on AKS

- .github/workflows/rbac-gen.yml
- .tekton/backplane-operator-main-unit-test.yaml
Adding pipleine config to execute `unit-test` job in `konflux`.
https://issues.redhat.com/browse/ACM-14840
Added `.tekton` file for unit testing in `konflux`.
> [ACM-14840] Added unit-test job for konflux

- controllers/backplaneconfig_controller.go
- controllers/toggle_components_test.go
>  remove hypershift-preview resources

- pkg/templates/charts/hosting/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-controller.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-webhook.yaml
Refer to https://issues.redhat.com/browse/ACM-16213, remove limits for current hub controllers that have them
https://issues.redhat.com/browse/ACM-16203 
> remove limit for server foundation components

- sonar-project.properties
To provide a more accurate assessment of our code quality, we will exclude YAML files from the analysis in this repository. These files currently include manifests from other squads, which are skewing the quality score for the actual operator. We plan to reintroduce YAML scans at a later stage.
https://issues.redhat.com/browse/ACM-15881
Updated the exclusion list to include YAML files.
> [ACM-15881] Exclude YAML files from sonar scans

- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-controller.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
Refer to https://issues.redhat.com/browse/ACM-16213, remove limits for current hub controllers that have them
https://issues.redhat.com/browse/ACM-16203 
> remove GOMEMLIMIT for foundation components

- pkg/rendering/renderer.go
- pkg/utils/annotations.go
- pkg/utils/annotations_test.go
> Flight control annotation

- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-curator-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/clusterclaims-controller-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-controller-deployment.yaml
Remove resource limits from all CLC components including:
- cluster-curator
- cluster-image-set
- clusterclaims
- provider-credential
https://issues.redhat.com/browse/ACM-16345
> remove resource limits from all CLC components

- pkg/templates/charts/toggle/cluster-lifecycle/templates/provider-credential-controller-deployment.yaml
one resource limit was missed to remove from provider credential controller deployment
https://issues.redhat.com/browse/ACM-16345
/cc @fxiang1  @rokej
> remove resource limits from provider credential controller deployment

- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-controller-manager-deployment.yaml
> capa secret bug fix

- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-controller-manager-deployment.yaml
> test fix ocm.json permission ACM-18285

- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/config.yaml
Modified `bundle-automation` configuration files to enable support for the `backplane-2.9` branch.
https://issues.redhat.com/browse/ACM-17972
Updated `hack/bundle-automation/config.yaml` to `backplane-2.9`.
> [ACM-17972] Updated bundle-automation release branch ref to MCE 2.9

- .github/workflows/regenerate-charts.yml
- .github/workflows/regenerate-operator-bundles.yml
- .github/workflows/regenerate-sha-commit.yml
Modified `.github` configuration files to enable automation support for the `backplane-2.8` branch.
https://issues.redhat.com/browse/ACM-17970
Added `backplane-2.8` to `.github` config files.
> [ACM-17970] Updated GH actions config files to support 2.8 automation

- pkg/templates/charts/toggle/server-foundation/templates/clusterrole-foundation.yaml
- pkg/templates/rbac_gen.go
Support to get crd for foundation component
> support to get crd for foundation

- Makefile
- api/v1/multiclusterengine_webhook.go
- api/v1/multiclusterengine_webhook_test.go
- api/v1/webhook_suite_test.go
- api/v1/zz_generated.deepcopy.go
ValidateDelete now accepts labels for validating deletion of the MCE CR. A generic approach was implemented for future deletino exceptions based on labels
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @dislbenn  @cameronmwall`
/cc @dislbenn  @cameronmwall
> [ACM-18701] Added label-based validateDelete exceptions

- Makefile.dev
> Updated pipeline branch config for 2.9

- pkg/templates/crds/foundation/config.open-cluster-management.io_klusterletconfigs_crd.yaml
Update the KlusteletConfig CRD to latest version.
Jira: https://issues.redhat.com/browse/ACM-18805 
> Sync latest KlusterletConfig CRD from cluster-lifecycle-api

- controllers/backplaneconfig_controller.go
- pkg/utils/annotations.go
- pkg/utils/annotations_test.go
> allow some resources to be editable

- api/v1/multiclusterengine_webhook.go
- api/v1/multiclusterengine_webhook_test.go
> Fixed webhook bug

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Some rbac needs to be updated for clusterpermissions in order for fine grained rbac feature
Related Issue
https://issues.redhat.com/browse/ACM-20546
> adding rbac for clusterpermissions

- api/v1/multiclusterengine_methods.go
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/suite_test.go
- controllers/toggle_components.go
- hack/bundle-automation/charts-config.yaml
- pkg/templates/charts/toggle/cluster-api-provider-openshift-assisted/templates/capoa-bootstrap-controller-manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-api-provider-openshift-assisted/templates/capoa-controlplane-controller-manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-api-provider-openshift-assisted/values.yaml
- pkg/toggle/toggle.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
This adds a toggle for the capoa component. There was also a slight change in the charts based on how the images were onboarded
https://issues.redhat.com/browse/ACM-1971
> capoa toggle

- pkg/rendering/renderer.go
- pkg/utils/utils.go
Server foundation request the flag indicating that we are in upgrading status, so we are checking that the status of MCE as a different desired version from current version and passing that flag
https://issues.redhat.com/browse/ACM-20413
> add upgrading flag

- hack/bundle-automation/charts-config.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-controller-manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-api/values.yaml
Updated chart automation for capi webhook
> Updated chart automation imageMappings for capi

- pkg/utils/utils.go
- pkg/utils/utils_test.go
Added new capi webhook image to the RBAC generation
> Added new capi webhook image to the RBAC generation

- pkg/utils/utils.go
https://issues.redhat.com/browse/ACM-21190
> upgrading flag bug fix

- hack/bundle-automation/charts-config.yaml
- pkg/templates/charts/toggle/cluster-api/templates/mce-capi-webhook-config-deployment.yaml
- pkg/templates/charts/toggle/cluster-api/values.yaml
- pkg/utils/utils.go
> renamed image ref in capi chart

- hack/bundle-automation/charts-config.yaml
- pkg/templates/charts/toggle/cluster-api/templates/mce-capi-webhook-config-deployment.yaml
- pkg/templates/charts/toggle/cluster-api/values.yaml
- pkg/utils/utils.go
This reverts commit 4b7049d0cda87af997d6bff5f5a19fda68c474db.
> Revert "renamed image ref in capi chart"

- .gitignore
- hack/bundle-automation/config.yaml
Update hive commit 2.7.5
https://issues.redhat.com/browse/ACM-21946
> [ACM-21946] Update hive commit 2.7.5

- pkg/rendering/renderer.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
Provides a helm flag that can be used when rendering charts if an EUS upgrade is taking place
https://issues.redhat.com/browse/ACM-23544?filter=-1
> EUS upgrading flag

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
- pkg/utils/utils_test.go
rbac for console clusterrole needs to be updated similar to https://github.com/stolostron/backplane-operator/pull/1507 for clusterpermissions
https://issues.redhat.com/browse/ACM-24164
Adding permissions for the new component multicluster-role-assignment in the console-mce clusterrole
> adding permissions of mcra to console chart

- pkg/templates/charts/hosted/server-foundation/templates/managedcluster-import-role.yaml
Update import-controller rbac 
https://issues.redhat.com/browse/ACM-23612
> update import-controller rbac
