- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- test/function_tests/backplane_operator_install_test/backplane_operator_install_test.go
Issue: https://github.com/open-cluster-management/backlog/issues/15630
Add ownerrefences to all resources and remove deletes from finalizer logic
that can be handled by garbage collection.
> Use ownerreferences to handle cleanup

- .github/workflows/regenerate-operator-bundles.yml
- Makefile.dev
https://github.com/open-cluster-management/backlog/issues/15635
Trial runs shown here - 
https://github.com/zkayyali812/backplane-operator/actions
Open to suggestions about perhaps including different title/message?
Leveraging - https://github.com/marketplace/actions/create-pull-request
With this strategy, it would create a PR instead of committing directly to main. I figured it may be beneficial to have a manual review (at least for time being to ensure script functions as expected).
> 15635 Automation to update templates

- hack/scripts/dev-update-image-references.py
Reclone pipeline on each run. Gather from backplane-pipeline repo (rather than pipeline repo).
> Fetch images from backplane pipeline

- api/v1alpha1/multiclusterengine_types.go
- controllers/backplaneconfig_controller.go
- pkg/status/condition.go
- pkg/status/status.go
Display uninstall status in phase when mce is deleted. Report an error
if mce is stuck waiting for clustermanager to clean up after five minutes.
> Report status while mce uninstalls

- controllers/backplaneconfig_controller.go
- pkg/status/status.go
The status manager is linked to the MultiClusterEngineReconciler and tracks
components added during reconciliation. To track status on an MCE basis the
manager should be reset on each new MCE reconciled, which can be traced via
UID.
> Track UID in status manager

- pkg/templates/core/validatingwebhook.yaml
Webhook wasn't functioning because it was configured for v1alpha1 rather than the new v1 MCE apiversion
> Configure webhook for mce v1

- hack/bundle-automation/charts-config.yaml
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
Related issue: https://github.com/stolostron/backlog/issues/19275
> redoing chart link to use https instead of ssh

- pkg/templates/charts/toggle/server-foundation/templates/clusterrole-foundation-agent.yaml
fix the issue: https://github.com/stolostron/backlog/issues/21190
only update the yaml in chart because the lease rabc has been in backplaneconfig_controler.go.
> add lease rbac for work-manger addon agent in ocp 311 case

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
CRD gets a new ObjectRef when doing final release vendoring from `hypershift:release-4.10`
> New objectRef, resulted from final hypershift:release-4.10 vendoring

- pkg/templates/crds/hypershift/cluster.open-cluster-management.io_hypershiftdeployments.yaml
Signed-off-by: Roke Jung <roke@redhat.com>
Make spec.infrastructure.cloudProvider optional
https://github.com/stolostron/backlog/issues/22814
https://issues.redhat.com/browse/ACM-1407
> make spec.infrastructure.cloudProvider optional

- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
fix issue: https://github.com/stolostron/backlog/issues/22335
> increase the mem limit to fix the ocm-proxyserver oom in 2k clusters

- hack/bundle-automation/config.yaml
- hack/bundle-automation/gen-hive-bundle.sh
- hack/bundle-automation/generate-bundles.py
- hack/bundle-automation/requirements.txt
Over time, we have been gradually moving away from the approach of getting bundle input from the `community-operators` repo, and instead getting it from other sources.   The initial rationale behind using `community-operators` as the source of truth never fully panned out (namely, that all parts of the productized ACM would be posted as individual piece parts to `community-operators` to allow a "assemble it yourself" approach).  And getting input from other places  can improve turnaround time on component updates and eliminates the burden of posting to `community-operators` as a required step.
This PR moves our approach for Hive away from "use community operators" approach to one where instead we will get Hive input material by generating their bundle using a tool the Hive team maintains. …
> Extend bundle automation to allow generation of input bundle via a tool

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
Missing from https://github.com/stolostron/backplane-operator/pull/238
> Add permission for ingress resource

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
for https://github.com/stolostron/backlog/issues/24465
> Hypershift deployment controller needs clusterset and setbinding permissions when the cluster security flag is enabled

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
- pkg/templates/rbac_gen.go
When the cluster security flag is enabled (which is off by default), Hypershift deployment controller needs additional clusterset and setbinding permissions.
for https://github.com/stolostron/backlog/issues/24472
> Hypershift deployment controller needs additional clusterset and setbinding permissions

- controllers/backplaneconfig_controller.go
https://github.com/stolostron/backlog/issues/24532
We create a namespace for global clusterset by default in https://github.com/stolostron/multicloud-operators-foundation/blob/80908de299379974ecbbd68a7452ec18b34f6a6b/pkg/controllers/clusterset/globalclusterset/globalset_controller.go#L150
And it's difficult to delete it in multicloud-operators-foundation part, the only way is deleting it in this repo.
> Delete global set namespace

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
https://github.com/stolostron/backlog/issues/24807
> Fix: cluster-proxy-addon install namespace on agent should be `open-cluster-management-agent-addon`

- pkg/templates/crds/cluster-lifecycle/cluster.open-cluster-management.io_clustercurators.yaml
For https://issues.redhat.com/browse/ACM-1260 https://github.com/stolostron/backlog/issues/26872
This PR should be merged ahead of https://github.com/stolostron/cluster-curator-controller/pull/137
because the API change is optional so it will not impact MCE during the run but the controller relies on the API to be there.
> Update Cluster Curator to add optional HookType field to support Ansible Workflow Job invocation

- config/rbac/role.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-deployment.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-rolebinding.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/cluster-image-set-service_account.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/values.yaml
- pkg/templates/rbac_gen.go
- pkg/utils/utils.go
This PR replaces https://github.com/stolostron/backplane-operator/pull/334 because I could update the message to a merge to include the signoff, which is required by the dco task.
> Add manifests for the new cluster imageset controller

- pkg/templates/charts/toggle/server-foundation/templates/ocm-webhook.yaml
Fixes: https://issues.redhat.com/browse/ACM-2305
> Fix: raise ocm-webook memory limit to 2Gi.

- pkg/templates/charts/toggle/console-mce/templates/console-deployment.yaml
https://github.com/stolostron/backlog/issues/22339
Use default failureThreshold (3)
Allow 5 seconds for timeout for hubs with large workloads
> Fix console-mce scale issues

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- controllers/backplaneconfig_controller.go
- pkg/status/condition.go
Cleans up hypershift-addon directly in finalizer function.
Jira: https://issues.redhat.com/browse/ACM-2289 
> Don't add ownerreference to hypershift-addon ManagedClusterAddOn

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/user-deployment.yaml
Fixes: https://issues.redhat.com/browse/ACM-2829
> Fix: cluster-proxy doesn't work in OCP proxy environment.

- controllers/toggle_components.go
- controllers/toggle_components_test.go
- pkg/status/generic.go
- pkg/status/generic_test.go
Jira: https://issues.redhat.com/browse/ACM-3514
On the off chance that the ClusterManagementAddon resource is not deployed while applying a component, it will be identified in the MCE.
In the status it will look like the below:
```
status:
components:
- kind: ClusterManagementAddOn
name: managed-serviceaccount
reason: ComponentsDeployed
status: "True"
type: Present
- kind: ClusterManagementAddOn
name: hypershift-addon
reason: ComponentsDeployed
status: "True"
type: Present
- kind: ClusterManagementAddOn
name: cluster-proxy
reason: ComponentsDeployed
status: "True"
type: Present
```
> ACM-3514 - track ClusterManagementAddons in toggleable component status

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
- pkg/templates/rbac_gen.go
Add a cluster role rule to list multiclusterengines to fix https://issues.redhat.com/browse/ACM-4230 and https://github.com/stolostron/backlog/issues/27211
> add RBAC to list multiclusterengines to fix ACM-4230

- pkg/status/local_cluster.go
Fix the bug that when user messes with mce toggle of local-cluster when it is owned by mch, it gets detached before the watch can correct the change. Add the status of detaching and set local-cluster available boolean to false to trigger mce to reconcile and reimport the local-cluster.
> adding local-cluster status to false when detaching

- hack/bundle-automation/generate-bundles.py
This commit updates the generate-bundle.py automation to insert "secompprofile: runtimedefault" into the pod security contexts generated when build charts from bundles via Zach's automation, to eliminate warnings about missing this security context setting.  
The change includes some reorg and style changes I could resist making when in the code.  The crux changes are in the function to insert Helm flow control, and the secompprofile stuff in the function that updates deployments.
A similar change will be made in the multiclusterhub-operator by a separate PR.
> Address secompprofile warnings in bundle-originated charts

- hack/bundle-automation/gen-hive-bundle.sh
Starting some time ago, our Generate Charts From Bundle (aka Zatch Technology(tm)) automation started failing when run for the Hive operator, with errors symptoms like this:
```
INFO:root:Running bundle-gen tool: ./hack/bundle-automation/gen-hive-bundle.sh mce-2.3 acfdebfb192b5f566562474f691e15259f87e794 /tmp/hive-operator-manifests
Cloning/checking out HIve repo at branch/commit (acfdebfb192b5f566562474f691e15259f87e794).
Cloning into 'hive'...
Updating files: 100% (31317/31317), done.
From https://github.com/openshift/hive
* branch                mce-2.3    -> FETCH_HEAD
Branch 'mce-2.3' set up to track remote branch 'mce-2.3' from 'origin'.
Switched to a new branch 'mce-2.3'
HEAD is now at acfdebfb1 Merge pull request #2027 from 2uasimojo/re-enable-autoscale
Running Hive bundle-gen …
```
> Fix not-valid-tip-of-branch errors when running gen-bundle for Hive

- pkg/templates/charts/toggle/assisted-service/templates/infrastructure-operator.yaml
- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager.yaml
- pkg/templates/charts/toggle/discovery-operator/templates/discovery-operator.yaml
- pkg/templates/charts/toggle/hive-operator/templates/hive-operator.yaml
This PR is the result of a manual bundle-to-chart run on the backplane-2.3 branch after the changes made by PRs #451 and #453 were merged into this branch.
This is *not* a cherry pick from a similar update done to the `main` branch since the `main` branch now already represetns the `backplane-2.4` release.
> Manual bundle-to-charts update for backplane-2.3

- pkg/templates/charts/toggle/assisted-service/templates/infrastructure-operator.yaml
- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager.yaml
- pkg/templates/charts/toggle/discovery-operator/templates/discovery-operator.yaml
- pkg/templates/charts/toggle/hive-operator/templates/hive-operator.yaml
DO NOT CHERRY PICK INTO BACKPLANE-2.3
This PR is the result of a manual bundle-to-chart run on the main branch after the changes made by PRs #450 and #452 were merged into this branch.
This is a main-branch counterpart to already-merged PR #454.  It should NOT be cherry picked into the backplane-2.3 branch as that update has already been done.  (It is necessary to do separate updates since the main branch has moved to representing the next-release (2.4) of MCE and the config for doing the bundle-to-chart generation will now differ between the branches).
> Manual bundle-to-charts update for main branch

- hack/bundle-automation/config.yaml
- pkg/templates/crds/cluster-manager/operator.open-cluster-management.io_clustermanagers.yaml
The PR is for: https://issues.redhat.com/browse/ACM-5551
We consolidate server foundation code into one new repo - [the ocm repo](https://github.com/stolostron/ocm)
So the automation script must be updated as well.
> Update cluster manager bundle automation.

- main.go
This reverts commit 8948288b0b4e82269d83a06543c946b31123ab50.
Jira: https://issues.redhat.com/browse/ACM-5997
> Revert "Update webhook server tls min version to 1.3 (#427)"

- hack/bundle-automation/config.yaml
- hack/bundle-automation/generate-bundles.py
Assisted-service-operator was converted from packagemanifest to bundle format so the automated scripting has to update. It will now look through all annotation metadata files to find the latest bundle on the desired channel.
Jira: [ACM-6264](https://issues.redhat.com/browse/ACM-6264)
> Update generate bundles script

- OWNERS
- controllers/backplaneconfig_controller.go
In MCE 2.0, the sub-components were required to be adopted by the `MultiClusterEngine`, so those resources wouldn't be removed when MCH was deleted. These changes are no longer in the latest MCE versions.
> [ACM-3133] Removed MCE subcomponent adoption code

- main.go
Adding `olmv1alpha1` to scheme to register the kind for `ClusterServiceVersion`. Since this was missing, when `DISABLE_CLIENT_CACHE` is enabled, this will cause the `multicluster-engine-operator` pod to fail.
```
1.6934115950189047e+09 ERROR setup unable to start manager {"error": "no kind is registered for the type v1alpha1.ClusterServiceVersion in scheme \"pkg/runtime/scheme.go:100\""}
```
> [ACM-6981] Added olmv1alpha1 to scheme

- hack/bundle-automation/config.yaml
- hack/bundle-automation/generate-bundles.py
Assisted-service-operator was converted from packagemanifest to bundle format so the automated scripting has to update. It will now look through all annotation metadata files to find the latest bundle on the desired channel.
Original Jira: [ACM-6264](https://issues.redhat.com/browse/ACM-6264)
> [ACM-6910] Updated generate bundle scripts

- pkg/templates/charts/toggle/console-mce/templates/console-metrics-monitor-role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-metrics-monitor-rolebinding.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-service.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-servicemonitor.yaml
- pkg/templates/rbac_gen.go
The addition of the console ServiceMonitor will allow us to track a new metric added by console frontend to track user interactions with the various RHACM pages. This will increase transparency into how customers are interacting with the product.
https://issues.redhat.com/browse/ACM-6797
This PR adds a SerivceMonitor, Role & RoleBinding to the console-mce chart
> Add console ServiceMonitor for metric collection

- hack/bundle-automation/generate-charts.py
- pkg/templates/charts/toggle/managed-serviceaccount/templates/addontemplate.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/templates/clustermanagementaddon.yaml
- pkg/templates/managed-serviceaccount/crds/authentication.open-cluster-management.io_managedserviceaccounts.yaml
1. update the managedServiceAccount CRD
2. update the chart generate script to update chart version before rendering templates, this can make the generated addontemplate name with ACM version prefix.
https://issues.redhat.com/browse/ACM-7072
> update chart for managed-serviceaccount

- config/rbac/role.yaml
- pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml
- pkg/templates/rbac_gen.go
Add list permission for `multiclusterapplicationsetreports`, this is needed to support ArgoCD pull model in the app topology.
https://issues.redhat.com/browse/ACM-7389
Changed console-clusterrole by adding list permission for `multiclusterapplicationsetreports`
N/A
N/A
/cc @chenz4027
> ACM-7389 Add list permission for multiclusterapplicationsetreports

- controllers/backplaneconfig_controller_test.go
- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/generate-charts.py
- hack/unit-test-crds/addondeploymentconfigs.yaml
- hack/unit-test-crds/addontemplates.yaml
- pkg/rendering/renderer_test.go
- pkg/templates/charts/toggle/managed-serviceaccount/templates/addondeploymentconfig.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/templates/addontemplate.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/templates/clustermanagementaddon.yaml
Update chart for managed service account addon to:
- ignore the managedClusterAddon.spec.installNamespace for msa addon
- orphan the managedClusterAddon.spec.installNamespace on the managed cluster when deleting the addon
- Update permission config in addontemplate for the managed service account addon
https://issues.redhat.com/browse/ACM-7602
- update the `generate-charts.py` to change the addonDeploymentConfig namespace from value `{{ .Release.Namespace }}` to `{{ .Values.global.namespace }}` when syncing from the upstream repo
- sync managedServiceAccount chart from the upstream repo
/cc @dislbenn  @qiujian16
> Update chart for managed service account addon

- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
PR #511 made a change to `config/rbac/roles.yaml` to add permission for the `multiclusterapplicationsetreports` kind.  It committed some other files as well, but did not commit a change to the operator CSV in the  'bundle/manifests' directory.  This update is make if you run `make bundle` and is needed to ensure that the operator has the new permission when deployed by OLM.
This PR commits the bundle/manifest CSV change missed by PR #511.  If the ACM-7389 issue has been tested and found to be resolved its a mystery to me how things are working, as usually an operator can't provide permission downstream that it doesn't have itself.
> Commit bundle RBAC change not committed as part of PR 511

- pkg/templates/charts/toggle/console-mce/templates/console-prometheus-rules.yaml
- pkg/templates/rbac.go
Includes a PrometheusRule resource that exposes a metric: `acm_console_page_count:sum`. This metric sums all page visits across the ACM Console, and reduces the cardinality of the original metric so we can upload to Telemetry.
https://issues.redhat.com/browse/ACM-7492
The PR adds a PrometheusRule resource for the acm console. The PromRule resource will include one rule that sums page count visits across the console pods (running and previous).
> Console PrometheusRule for page visit counts

- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/uninstall.go
We have changed the location of the Service Monitor resource from `openshift-monitoring` to the mce namespace so the old resource needed to be removed on
[ACM-7676](https://issues.redhat.com/browse/ACM-7676)
In the reconcile loop we use a hardcoded delete to remove the resources from `openshift-monitoring`
> Remove service monitor from openshift-monitoring ns

- hack/bundle-automation/config.yaml
Our `regenerate-bundles` script was not pulling changes from assisted installer because the channels were not matched. Installer believes that `ocm-2.9` is the correct channel but we are changing to assisted installer's `ocm-2.10` to solve the issue until we come to a conclusion with assisted installer on what the proper channel should be
[ACM-7763](https://issues.redhat.com/browse/ACM-7736)
> temporary change to assisted service bundle channel

- api/v1/multiclusterengine_methods.go
- api/v1/multiclusterengine_methods_test.go
- controllers/backplaneconfig_controller.go
- controllers/uninstall.go
- pkg/utils/utils.go
Updated MCE operator to create a service and servicemonitor to allow OCP to begin collecting controller-runtime metrics for the operator.
https://issues.redhat.com/browse/ACM-8548
Updated MCE operator to deploy metrics service and servicemonitor to collect controller-runtime metrics.
/cc @ngraham20 @cameronmwall 
/hold
> [ACM-8548] Added service and servicemonitor to collect MCE operator metrics

- api/v1/multiclusterengine_types.go
- pkg/status/status.go
Updated MCE operator to show `Pending` status when the MCE CR has the `pause` annotation set to `true`.
https://issues.redhat.com/browse/ACM-9006
Updated MCE CR to show a Pending status when the MCE operator is paused.
> [ACM-9006] Updated multiclusterengine phase status to Paused when the operator is paused

- config/rbac/role.yaml
- controllers/backplaneconfig_controller.go
- controllers/hosted.go
- controllers/toggle_components.go
- controllers/uninstall.go
- hack/prereqs/oc.yaml
- pkg/foundation/cluster_manager.go
- pkg/foundation/hosted_cluster_manager.go
- pkg/rendering/renderer.go
- pkg/templates/rbac_gen.go
There was excess information in all logging statements. This has been removed
https://issues.redhat.com/browse/ACM-8351
Change the log function from `log.FromContext()` to `log.Log.WithName()`
> remove context from logs

- Makefile.dev
Update `Makefile.dev` linter job to use latest `installer-dev-tools` script.
> Switch lint-operator-bundles target to use generate-shell.py script

- pkg/templates/crds/foundation/config.open-cluster-management.io_klusterletconfigs_crd.yaml
This PR fixes the incorrect JSON field name of HubKubeAPIServerURL in KlusterletConfig CRD.
https://issues.redhat.com/browse/ACM-9711
> fix the incorrect json field name of KlusterletConfig

- hack/bundle-automation/charts-config.yaml
- hack/bundle-automation/generate-charts.py
- hack/unit-test-crds/clustermanagementaddons.addon.open-cluster-management.io.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/templates/clustermanagementaddon.yaml
- pkg/utils/utils.go
this PR will:
- Use install strategy to install managedserviceaccount addon(create managedclusteraddon CR) for all clusters
- Set the default value of maangedserviceaccount in the muilticlusterengine CR to true
https://issues.redhat.com/browse/ACM-9655
- update the `generate-charts.py` python script to inject install strategy into clustermanagementaddon for the managedserviceaccount addon
- move the managedserviceaccount from `offComponents` into `onComponents`
- update the `hack/unit-test-crds/clustermanagementaddons.addon.open-cluster-management.io.yaml` to make the e2e pass
Tag the appropriate reviewers who should review this …
> Enable managed service account addon by default

- api/v1/multiclusterengine_types.go
- controllers/backplaneconfig_controller.go
- pkg/status/condition.go
- pkg/status/condition_test.go
- pkg/status/status.go
Enhanced the MCE operator to capture and display status for when resources apply to fail within MCE.
https://issues.redhat.com/browse/ACM-8576
Updated the MCE status condition to include a reference to the failed resource and updated the status phase to reflect `error` when an issue arises.
/cc @ngraham20 @cameronmwall
> [ACM-8576] Updated MCE status response for resource applying

- .github/workflows/regenerate-operator-bundles.yml
Our regenerate-bundles workflow for the main branch (i.e. the active dev branch) is configured to run only once a day. That pace seems fine for branches that are shipped and in maintenance/support as bundle changes happen very infrequently (hopefully not at all) in the Z-Stream. But this pace seems way to slow for the in-dev branch, especially as we deal with end-of-sprint deadlines where changes show up.
This PR changes the main-branch frequency to every 2 hours from 6AM to 6PM EST.  If that proves too expensive re action-run quotas, we can consider backing off.
> chore: Increase frequency of regenerate-operator-bundle runs

- hack/bundle-automation/config.yaml
- hack/bundle-automation/requirements.txt
Adding `preserve_files` field to the IBIO component in the bundle-automation `config.yaml` file. This will allow the automation to reserve that file instead of removing it from the directory.
https://issues.redhat.com/browse/ACM-10099
Added `preserve_files` field to the IBIO component.
> [ACM-10099] Added preserve_files field to IBIO config

- controllers/backplaneconfig_controller.go
Added a warning log to indicate that a deprecated field is being used with the MCE CR spec.
https://issues.redhat.com/browse/ACM-10272
Added additional logging to check if deprecated fields are being used within MCE.
> [ACM-10272] Added warning logs for deprecated spec field usage

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-configmap.yaml
- pkg/templates/charts/toggle/hypershift/values.yaml
With https://issues.redhat.com/browse/HYPBLD-249, the following MCE container images are no longer built and packaged in MCE. This PR is to remove references to those images from the hypershift addon installation chart.
https://issues.redhat.com/browse/HYPBLD-249
With https://issues.redhat.com/browse/HYPBLD-249, the following MCE container images are no longer built and packaged in MCE. This PR is to remove references to those images from the hypershift addon installation char
> ACM-10734: Remove obsolete hypershift related image references

- controllers/backplaneconfig_controller.go
- pkg/utils/annotations.go
- pkg/utils/annotations_test.go
Added new annotation version and deprecating others.
| Deprecated                    | New                                            | Description                                                                                                     |
|-------------------------------|------------------------------------------------|-----------------------------------------------------------------------------------------------------------------|
| ignoreOCPVersion              | multicluster.openshift.io/ignore-ocp-version | Annotation used to indicate the operator should not check the OpenShift Container Platform (OCP) version before proceeding when set. |
| imageOverridesCM              | multicluster.openshift.io/image-overrides-configmap | Annotation used in multiclusterengine to specify …
> [ACM-10803] Deprecate and update MCE annotations

- Makefile
- config/rbac/role.yaml
- pkg/templates/rbac_gen.go
For Red Hat, there was an announcement made for us to use `podman` instead of `docker`; therefore, this PR will add the support for `podman` and keep the `docker` compatibility if it is still needed.
https://issues.redhat.com/browse/ACM-10819
Added supported `podman` configs in the Makefiles.
> [ACM-10819] Updated Makefiles to support podman configuration

- pkg/templates/crds/foundation/config.open-cluster-management.io_klusterletconfigs_crd.yaml
Update the KlusterletConfig CRD.
https://issues.redhat.com/browse/ACM-11239
Add a new field appliedManifestWorkEvictionGracePeriod to the KlusterletConfig CRD.
n/a
> update KlusterletConfig CRD

- config/rbac/role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
Import controller needs the creating events permission to send events.
https://issues.redhat.com/browse/ACM-10730
https://github.com/stolostron/managedcluster-import-controller/pull/327
Add creating events permission for the import controller
@dislbenn @zhiweiyin318 @elgnay
> Update import controller rbac

- controllers/backplaneconfig_controller_test.go
- controllers/toggle_components.go
- controllers/uninstall.go
- pkg/rendering/renderer_test.go
- pkg/templates/charts/toggle/managed-serviceaccount/templates/addondeploymentconfig.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/templates/addontemplate.yaml
- pkg/templates/charts/toggle/managed-serviceaccount/templates/clustermanagementaddon.yaml
Remove the default addondeploymentconfig for the managedserviceaccount addon to fix the upgrade issue introduced by the PR https://github.com/stolostron/backplane-operator/pull/705
https://issues.redhat.com/browse/ACM-11655
- address TODOs for the managed service account addon
- remove the default  addondeploymentcondig for the msa addon
- regerate charts for the msa
/cc @dislbenn @qiujian16
> Remove the default addondeploymentconfig for the managedserviceaccount addon

- pkg/templates/crds/cluster-lifecycle/cluster.open-cluster-management.io_clustercurators.yaml
Updated the ClusterCurator CRD to support the EUS to EUS upgrade feature for managed clusters.
https://issues.redhat.com/browse/ACM-10683
Updated the ClusterCurator CRD, added a `spec.upgrade.intermediateUpdate` field for users to specify the intermediate upgrade version.
N/A
> ACM-10683 Update ClusterCurator CRD to support EUS upgrades

- pkg/rendering/renderer.go
- pkg/templates/charts/toggle/cluster-manager/templates/cluster-manager.yaml
- pkg/templates/charts/toggle/cluster-manager/values.yaml
- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager-deployment.yaml
- pkg/templates/charts/toggle/hypershift/values.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-route.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-service.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-clusterview-api-svc-v1alpha1.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-clusterview-api-svc.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-controller.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver-api-svc.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver-svc.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-proxyserver.yaml
- pkg/templates/charts/toggle/server-foundation/templates/ocm-webhook.yaml
- pkg/templates/charts/toggle/server-foundation/values.yaml
add deployOnOCP field to the charts to support deploy on aks.
on aks case only need cluster-manager, foundation, hypershift components.
https://issues.redhat.com/browse/ACM-11040
> add deployOnOCP field to the charts to support deploy on aks

- hack/unit-test-crds/prometheusrule.yaml
- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-prometheusrule.yaml
Per request from the OpenShift monitoring team, add a recording rule acm_managed_cluster_worker_cores:sum, which will be sent to telemeter side.
- https://issues.redhat.com/browse/ACM-11628
- https://issues.redhat.com/browse/MON-3884
Deploy a PrometheusRule when installing clusterlifecycle-state-metrics-v2. It includes a recording rule acm_managed_cluster_worker_cores:sum, which will be sent to telemeter side instead of the raw metric.
n/a
~~- [ ] I have updated the documentation (if necessary) to reflect the changes.~~
n/a
> add a recording rule for clusterlifecycle-state-metrics

- hack/bundle-automation/config.yaml
In order to address some FIPS-related issue, the assisted service image is being built both on a RHEL8 and RHEL9 base in MCE 2.6.  These two images will be represented by new image keys `assisted_service_8` and `assisted_service_9` (and the previous unsuffixed key `assisted_service` will no longer be used).  
- Our Jira ticket for the change: [ACM-11781](https://issues.redhat.com/browse/ACM-11781)
- Change to assisted service CSV to add a new env var:  [asisted-service PR 6349](https://github.com/openshift/assisted-service/pull/6349) (merged into their release-ocm-2.11 branch)
This PR updates the image mappings in the bundle-to-chart transform config.
> Adjust assisted service image mappings [ACM-11781]

- bundle.Dockerfile
- bundle/manifests/multicluster-engine.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
- config/manifests/bases/multicluster-engine.clusterserviceversion.yaml
- config/rbac/role.yaml
- pkg/templates/crds/cluster-lifecycle/cluster.open-cluster-management.io_clustercurators.yaml
- pkg/templates/rbac_gen.go
Add XValidation to the upgrade option in the ClusterCurator CRD. This performs various validations against the `intermediateUpdate` and `desiredUpdate` fields.
I only changed the ClusterCurator CRD, but looks like previous commits to the repo didn't run `go generate` and `make bundle` so that's why there are many other files changed.
https://issues.redhat.com/browse/ACM-10683 - ClusterCurator EUS to EUS upgrade
- Make sure intermediateUpdate is immutable but if it was not present then it shouldn't be allowed to be added afterwards
- Make sure desiredUpdate is only immutable when intermediateVersion is present because we don't want to change the current behaviour which allows users change desiredUpdate after creating the CR
- Make sure intermediateUpdate cannot be by itself when …
> ACM-10683 Add XValidation to ClusterCurator CRD

- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-prometheusrule.yaml
Use max() instead of sum() in the foundation recording rule
https://issues.redhat.com/browse/ACM-11971
Use max() instead of sum() in the foundation recording rule
n/a
~~- [ ] I have updated the documentation (if necessary) to reflect the changes.~~
~~- [ ] I have added/updated relevant unit tests (if applicable).~~
> update foundation recording rule

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
This PR change rollout strategy of cluster-proxy-addon-manager to be "Recreate".
https://issues.redhat.com/browse/ACM-11947
cluster-proxy-addon-manager doesn't using leader election to start controller, so in upgrade case from 2.10 to 2.11, the old pod and new pod will override the managedclusteraddon with different value. Which will create many CSRs and cause cluster-proxy-addon pending.
In 2.11, we have to turn the rollout strategy to "Recreate" to avoid new pods and old pods run together, we also working on adding leaderelection on cluster-proxy-addon-manager.
Tag the appropriate reviewers who should review this pull request. …
> Using recreate strategy in cluster-proxy-addon-manager.

- hack/bundle-automation/generate-shell.py
Changing the repository path back to `stolostron`. It is currently pointing towards a forked repository.
> Revert shell script org to stolostron

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/manager-deployment.yaml
"Recreate" is forbidden on OCP platform.
```
message: 'error applying object Name: cluster-proxy-addon-manager Kind: Deployment
Error: Deployment.apps "cluster-proxy-addon-manager" is invalid: spec.strategy.rollingUpdate:
Forbidden: may not be specified when strategy `type` is ''Recreate'''
```
https://issues.redhat.com/browse/ACM-11989
> Revert cluster-proxy rollout strategy change.

- hack/bundle-automation/generate-charts.py
- pkg/templates/charts/toggle/managed-serviceaccount/templates/addontemplate.yaml
Add the annotation `target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'` to deployments in the managedserviceaccount addonTemplates. 
https://issues.redhat.com/browse/ACM-11315
> Inject annotations for deployments in addonTemplates

- .github/workflows/regenerate-sha-commit.yml
- hack/bundle-automation/config.yaml
Added support for Personal Access Token (PAT) for the regenerate sha commit script. When pulling from a private  repository, you need to provide a token for the github action to clone the private repository.
Added `env` for `GH_READ_PAT` for `regenerate-sha-commit` script.
> Added PAT support for regenerate-sha-commit script

- controllers/backplaneconfig_controller.go
In MCE 2.4, a regression introduced into our code: https://github.com/stolostron/backplane-operator/blob/backplane-2.4/controllers/backplaneconfig_controller.go#L232-L242.
We are attempting to apply the `openshift.io/cluster-monitoring` label to the `targetNamespace` before it is created by the MCE operator. Beforehand, if the `targetNamespace` did not exist, MCE would create it; however, since we are trying to apply the label before that validation happens, the regression was introduced. This PR will fix that issue by moving the label apply later on in the reconcile loop.
https://issues.redhat.com/browse/ACM-12132
Updated order for applying label for MCE operand's namespace.
Add any additional notes, context, or …
> [ACM-12132] Fixed standalone mce failing to install on custom namespace

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
- pkg/templates/rbac_gen.go
The hypershift addon manager needs to get its pod to get the list of its tolerations and pass them down to the HCP CLI deployment.
Added get and list rule for pods.
> ACM-11310: want to get and list pods

- api/v1/multiclusterengine_types.go
- bundle/manifests/multicluster.openshift.io_multiclusterengines.yaml
- config/crd/bases/multicluster.openshift.io_multiclusterengines.yaml
Added `currentVersion` and `desiredVersion` to the `additionalPrinterColumns` in MCE CRD.
https://issues.redhat.com/browse/ACM-12431
Added support to print out the `currentVersion` and `desiredVersion` of the MCE operator.
> [ACM-12431] Added MultiClusterEngine current and desired version columns to MCE CRD

- config/crd/internal/internal-hub-component.yaml
Added CRD. Operator does not interact with it yet.
> Internalhubcomponent

- api/v1/multiclusterengine_methods.go
- controllers/backplaneconfig_controller.go
- pkg/utils/utils.go
In MCE 2.7, IBIO will GA this release; therefore, we are updating the IBIO component to reflect the new status.
https://issues.redhat.com/browse/ACM-13136
Updated MCE to use IBIO GA version and remove preview version.
> [ACM-13136] Updated IBIO component to GA status

- pkg/templates/charts/toggle/hypershift/Chart.yaml
Since the hypershift feature is not preview, I am removing -preview from the chart name.
https://issues.redhat.com/browse/ACM-14534
> ACM-14534: remove -preview from the hypershift chart name

- controllers/backplaneconfig_controller.go
In the MCE operator, we would see that there is a `lstat` error that states the `pkg/templates/crds` dir does not exist. This was occurring because there was a white space at the beginning of the value we were setting for the crdsDir path.
Removed the white space from the beginning of the `crdDirs` value.
> Fixed lstat error for crdsDirs path

- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/toggle_components.go
Updated the `backplane-operator` finalization to include checking for the `local-cluster` namespace. If the `local-cluster` namespace is not deleted, then MCE will stall when it comes to uninstalling the operator and operands.
https://issues.redhat.com/browse/ACM-11155
Updated operator to check for `local-cluster` namespace during uninstall.
> [ACM-11155] Added finalizer condition to check if local-cluster namespace was deleted

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-configmap.yaml
- pkg/templates/charts/toggle/hypershift/values.yaml
- pkg/utils/utils.go
- pkg/utils/utils_test.go
In MCE 2.4, the `cluster_api_provider_azure` key was unused and removed; therefore, this PR will remove the remaining image key references for the `hypershift-addon` component.
https://issues.redhat.com/browse/ACM-15089
Removed `cluster_api_provider_azure` image ref key.
> [ACM-15089] Removed cluster-api-provider-azure image key ref

- config/rbac/role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
Add get list hostedcluster permission for import controller, import controller needs to check if there are hostedclusters exist in the managedcluster namespace before deleting the namespace. 
- https://github.com/stolostron/managedcluster-import-controller/pull/406
- https://issues.redhat.com/browse/ACM-15059
> Foundation: Add get list hostedcluster permission for import controller

- controllers/backplaneconfig_controller.go
- controllers/toggle_components_test.go
on upgrading MCE from 2.6 to 2.7 the chart name changes for the hyper shift component by removing the preview flag. Several rbac resources use the chart name in their resource name and so are duplicated or left lingering when disabling the component
https://issues.redhat.com/browse/ACM-15425
When pruning the hyper-shift-preview component the controller now explicitly looks for the lingering resources and deletes them if they exist
> Remove lingering hypershift-preview resources on upgrade

- controllers/backplaneconfig_controller.go
ClusterManager brings the addons up, and the `CanInstallAddons` actually checks ClusterManager itself. This removed a feedback loop that prevented all addons from deploying
> Fixed ClusterManager bug

- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-configmap.yaml
The hypershift operator uses `cluster-api` container image from the hosted cluster's OCP payload instead of using the one that is packaged as part of MCE. Before removing the image from MCE, the image reference should be removed from the chart first.
> Remove cluster-api image reference from hypershift addon chart

- controllers/backplaneconfig_controller.go
Added a conditional check to validate if the `ClusterManagementAddOn` CRD is available on the cluster before deploying addon components in MCE.
Backport of PR: #1113
https://issues.redhat.com/browse/ACM-15739
Added check for CMAO CRD before deploying MCE addon related components.
> [ACM-15739] Added addon check before addon components

- api/v1/multiclusterengine_methods.go
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/suite_test.go
- controllers/toggle_components.go
- docs/available-components.md
- pkg/templates/charts/toggle/cluster-api/templates/capi-controller-manager-deployment.yaml
- pkg/templates/rbac.go
- pkg/toggle/toggle.go
- pkg/utils/utils.go
Updated MCE operator to support new `cluster-api` (CAPI) component.
Follow up to #1127 PR.
https://issues.redhat.com/browse/ACM-13577
Added new toggle for enable/disabling `cluster-api` component within MCE.
> [ACM-13577] Onboarded cluster-api (CAPI) component to MCE 2.8

- api/v1/multiclusterengine_methods.go
- controllers/backplaneconfig_controller.go
- controllers/backplaneconfig_controller_test.go
- controllers/suite_test.go
- controllers/toggle_components.go
- docs/available-components.md
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-controller-manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-leader-elect-role-role.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-leader-elect-rolebinding-rolebinding.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-manager-bootstrap-credentials-secret.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-manager-rolebinding-clusterrolebinding.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-metrics-service-service.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-validating-webhook-configuration-validatingwebhookconfiguration.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/templates/capa-webhook-service-service.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-admin-rolebinding-clusterrolebinding.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-leader-election-role-role.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-leader-election-rolebinding-rolebinding.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-manager-rolebinding-clusterrolebinding.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-validating-webhook-configuration-validatingwebhookconfiguration.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-webhook-service-service.yaml
- pkg/toggle/toggle.go
- pkg/utils/utils.go
Updated MCE operator to support new `cluster-api-provider-aws` (CAPA) component.
Follow up to #1128 PR.
https://issues.redhat.com/browse/ACM-13578
Added new toggle for enable/disabling `cluster-api-provider-aws` component within MCE.
> [ACM-13578] Onboarded cluster-api-provider-aws (CAPA) component to MCE 2.8

- config/rbac/role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-deployment.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
> Support flightctl integration (import-controller part).

- build/Dockerfile.prow
- build/Dockerfile.rhtap
- build/Dockerfile.test.prow
Moving the `prow` and `rhtap` Dockerfiles to the `build` directory. This change is just to remain consistent across our repositories.
> Added prow/konflux Dockerfiles to ./build dir

- config/crd/bases/authentication.open-cluster-management.io_managedserviceaccounts.yaml
- pkg/rendering/renderer.go
- pkg/utils/annotations.go
- pkg/utils/annotations_test.go
Issue: https://issues.redhat.com/browse/ACM-17576
Renaming all references to flight control to edge management per marketing decision. One reference remains in our rendering global struct. Will need to coordinate with server foundation to see when they arechanging their code
> rename edge management

- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-bootstrap-clusterrole.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-agent-registration-bootstrap-clusterrolebinding.yaml
- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
- Updated ClusterRole and ClusterRoleBinding names to remove the 'system:' prefix for consistency.
- Added new rules for 'clusters' resource under 'cluster.x-k8s.io' in managedcluster-import-role.yaml.
> Refactor managedcluster-import-role.yaml

- pkg/templates/charts/toggle/server-foundation/templates/managedcluster-import-role.yaml
- pkg/templates/rbac_gen.go
there is error logs in import controller pod 
`E0217 07:41:51.934808       1 reflector.go:158] "Unhandled Error" err="sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:108: Failed to watch *v1beta1.Cluster: unknown (get clusters.cluster.x-k8s.io)"
`
add clusters.cluster.x-k8s.io watch permission to import controller. 
> add clusters.cluster.x-k8s.io watch permission to import controller

- controllers/backplaneconfig_controller.go
When upgrading from 2.6 to 2.8, it was discovered that IBIO would be disabled, even if IBIO-preview had been enabled by the customer in 2.6, this PR will resolve that issue by ensuring that the GA version will inherit the preview version enabled status.
Related issue: https://issues.redhat.com/browse/ACM-18235
> [2.7][ACM-18235] Enable IBIO before prune IBIO-preview

- controllers/backplaneconfig_controller.go
When upgrading from 2.6 to 2.8, it was discovered that IBIO would be disabled, even if IBIO-preview had been enabled by the customer in 2.6, this PR will resolve that issue by ensuring that the GA version will inherit the preview version enabled status.
Related issue: https://issues.redhat.com/browse/ACM-18235
> [2.8][ACM-18235] Enable IBIO before prune IBIO-preview

- controllers/backplaneconfig_controller.go
When upgrading from 2.6 to 2.8, it was discovered that IBIO would be disabled, even if IBIO-preview had been enabled by the customer in 2.6, this PR will resolve that issue by ensuring that the GA version will inherit the preview version enabled status.
Related issue: https://issues.redhat.com/browse/ACM-18235
> [ACM-18235] Enable IBIO before prune IBIO-preview

- config/rbac/role.yaml
- pkg/templates/charts/toggle/server-foundation/templates/clusterrole-foundation.yaml
- pkg/templates/rbac_gen.go
The server foundation controller need to list/get/watch the cluster-permssion to find the kubevirt project list 
Add cluster-permssion list/get/watch permissions for server foundation controller
> support to list cluster permissions

- pkg/templates/charts/toggle/cluster-proxy-addon/templates/clusterrole.yaml
- pkg/templates/rbac_gen.go
The cluster-proxy-addon requires permission to send tokenview to the hub in order to verify if the request comes from an authenticated user and retrieve the UserInfo.
This PR is related to https://issues.redhat.com/browse/ACM-15712
> Add tokenreview permission for cluster-proxy.

- pkg/templates/crds/foundation/config.open-cluster-management.io_klusterletconfigs_crd.yaml
Update klusterletaddonconfig crd to make the maximum number of cluster claims configurable
https://issues.redhat.com/browse/ACM-20141
> Update klusterletaddonconfig crd

- api/v1/multiclusterengine_webhook.go
- api/v1/multiclusterengine_webhook_test.go
Setting Spec.LocalClusterName should be blocked if local-cluster resource exists (is enabled)
> ValidateUpdate now blocks renaming local-cluster

- api/v1/multiclusterengine_methods.go
- api/v1/multiclusterengine_webhook.go
- api/v1/multiclusterengine_webhook_test.go
- pkg/utils/utils.go
Webhook should block updating local-cluster name if managed by ACM
> [ACM-20312] Webhook should block updating local-cluster name if managed by ACM

- controllers/toggle_components.go
https://issues.redhat.com/browse/ACM-11500
When cluster-proxy pods are failing, the MCE status still reports as "Available" (false positive)
> ACM-11500 Changed cluster-proxy condition to DeploymentStatus

- api/v1/multiclusterengine_webhook.go
- api/v1/multiclusterengine_webhook_test.go
Through speaking with other teams and QE, it seems that exceeding 39 characters in length (yes 39, not 34) will cause MCE installed components to fail due to how components tack on information to existing resource names, causing them to exceed the Kubernetes allowed 63 character limit. The 34 character limit is to make sure that we don't get close to that number.
Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following …
> Cap local-cluster name to 34 chars

- config/rbac/role.yaml
- hack/bundle-automation/charts-config.yaml
- pkg/templates/charts/toggle/cluster-api-provider-aws/Chart.yaml
- pkg/templates/charts/toggle/cluster-api-provider-metal3/Chart.yaml
- pkg/templates/charts/toggle/cluster-api-provider-openshift-assisted/Chart.yaml
- pkg/templates/charts/toggle/cluster-api/Chart.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-controller-manager-deployment.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-manager-role-clusterrole.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-mutating-webhook-configuration-mutatingwebhookconfiguration.yaml
- pkg/templates/charts/toggle/cluster-api/templates/capi-validating-webhook-configuration-validatingwebhookconfiguration.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_clusterclasses.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_clusterresourcesetbindings.addons.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_clusterresourcesets.addons.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_clusters.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_extensionconfigs.runtime.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_machinedeployments.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_machinedrainrules.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_machinehealthchecks.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_machinepools.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_machines.cluster.x-k8s.io.yaml
- pkg/templates/crds/cluster-api/apiextensions.k8s.io_v1_customresourcedefinition_machinesets.cluster.x-k8s.io.yaml
- pkg/templates/rbac_gen.go
Updated cluster-api-installer branch ref to target backplane-2.9 instead of main, as the main branch has already moved on to targeting 2.10
> Updated cluster-api-installer branch ref to target backplane-2.9 instead of main

- controllers/backplaneconfig_controller.go
ACM-21450: MCE operator fails to uninstall when the ManagedCluster CRD is missing from the cluster. Add specific error check to catch this during uninstall.
https://issues.redhat.com/browse/ACM-21450
> [ACM-21450] Added missing CRD check to backplane uninstall

- pkg/templates/charts/toggle/cluster-lifecycle/templates/metrics-clusterrole.yaml
- pkg/templates/rbac_gen.go
Add additional permission to clusterlifecycle-state-metrics to access Hive ClusterDeployment API.
https://issues.redhat.com/browse/ACM-21189
Add list/watch ClusterDeployment permission to clusterlifecycle-state-metrics.
> [backplane-2.8] add additional permisson to clusterlifecycle-state-metrics

- build/Dockerfile.rhtap
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
> chore(KONFLUX-6210): fix and set name and cpe label for backplane-operator-mce-29

- config/rbac/role.yaml
- pkg/templates/charts/toggle/hypershift/templates/hypershift-addon-manager_clusterrole.yaml
- pkg/templates/rbac_gen.go
This is related to ACM-24682: configure ACM to import MCE, expanding the hypershift addon manager's permissions to handle namespace operations, manage addon deployment configurations, and work with klusterlet configurations - all necessary for the ACM to MCE import functionality.
https://issues.redhat.com/browse/ACM-24682
- Added namespace permissions 
- Expanded addondeploymentconfigs permissions
- Added klusterletconfigs permissions 
> ACM-24682: configure ACM to import MCE
